### ISSUE TITLE
Could not find Developer Disk Image

### ISSUE THREAD

**Issue by alrakaf** [eni9889/ppsideloader#101]
when i try to run the project "Could not find Developer Disk Image" 
on my 5S ios10 .

**Comment by benjibobs** [comment]
Please sideload using xcode 8 beta, this fixed the issue for me on iOS 10

**Comment by alrakaf** [comment]
> thank you so much i will try it

**Comment by benjibobs** [comment]
get back to me when you have

On 18 Jun 2016, at 5:57 pm, alrakaf <notifications@github.com<mailto:notifications@github.com>> wrote:


thank you so much i will try it

-
