### ISSUE TITLE
snapchat crashes on open

### ISSUE THREAD

**Issue by PacksGamingHD** [eni9889/ppsideloader#102]
it builds but when i open it it doesn't work

dyld: Library not loaded: @executable_path/pptweak.dylib
  Referenced from: /var/containers/Bundle/Application/DF0B0D97-8EE1-483D-8FC7-3E9F4D99A9D6/ppsideloader.app/Snapchat
  Reason: no suitable image found.  Did find:
    /var/containers/Bundle/Application/DF0B0D97-8EE1-483D-8FC7-3E9F4D99A9D6/ppsideloader.app/pptweak.dylib: mmap() errno=1 validating first page of '/var/containers/Bundle/Application/DF0B0D97-8EE1-483D-8FC7-3E9F4D99A9D6/ppsideloader.app/pptweak.dylib'
    /private/var/containers/Bundle/Application/DF0B0D97-8EE1-483D-8FC7-3E9F4D99A9D6/ppsideloader.app/pptweak.dylib: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/DF0B0D97-8EE1-483D-8FC7-3E9F4D99A9D6/ppsideloader.app/pptweak.dylib'

**Comment by ik4ito** [comment]
Remove all Provisioning Profile, then try again.
