### ISSUE TITLE
Facebook ios 9.3.2

### ISSUE THREAD

**Issue by h00157317** [eni9889/ppsideloader#103]
I have tried many versions but once I intalled it crashes immediately! Can anyone helps..

**Comment by mastermark1983** [comment]
same problem here

**Comment by joeafflitto** [comment]
Hey,
you getting any error codes while compiling the build in Xcode?

Thanks,
Joe

**Comment by h00157317** [comment]
No errors at all, it installed successfully.
Until It tries to open up and than it crashes immediately.
I have trying many different versions but the same thing keep happening!

**Comment by joeafflitto** [comment]
Is your certificate valid?

**Comment by h00157317** [comment]
Yes, i have installed other app like snapchat and youtube the only app that I gave issue on it is facebook

**Comment by al-muftah** [comment]
you are not alone, same issue here

**Comment by joeafflitto** [comment]
Where are you all getting your IPA files from?

**Comment by h00157317** [comment]
Appcake

**Comment by mastermark1983** [comment]
Same problem with the latest Facebook

**Comment by M202A1** [comment]
Tried 58.0 , 57.0 both sprung off

**Comment by M202A1** [comment]
I'm getting this error....

dyld: Library not loaded: /usr/lib/libuasharedanaltyics.dylib
  Referenced from: /var/containers/Bundle/Application/82901BCE-D5C

**Comment by saud978** [comment]
The error message is
=====
dyld: Library not loaded: /usr/lib/libuasharedanaltyics.dylib
  Referenced from: /var/containers/Bundle/Application/453B9A46-1BBC-42EF-88C4-A14E4C42F7D0/ppsideloader.app/pptweak.dylib
  Reason: image not found
