### ISSUE TITLE
An App ID with Identifier 'SnapchatPlus' is not available. Please enter a different string.

### ISSUE THREAD

**Issue by raytality** [eni9889/ppsideloader#104]
Can anyone help me?!

**Comment by joeafflitto** [comment]
This can be anything that hasn't been picked before. It's like a username, no two can be alike.

**Comment by ik4ito** [comment]
Make sure to remove the app from the phone before tweaking it, if still not working download the app in ur phone and delete it again, then try once again. *English isn't my native language*
