### ISSUE TITLE
security: unable to open "/Users/alex/Library/MobileDevice/Provisioning Profiles/.mobileprovision" for reading: No such file or directory

### ISSUE THREAD

**Issue by unopen** [eni9889/ppsideloader#105]
security: unable to open "/Users/alex/Library/MobileDevice/Provisioning Profiles/.mobileprovision" for reading: No such file or directory says there a problem dont know how to fix it this is for Snapchat++

**Comment by ik4ito** [comment]
Try re-downloading the ppsideloader file again

**Comment by likenew** [comment]
Same problem

**Comment by 13XxM1CHA3lxX37** [comment]
same here. Only for build in Simulator
