### ISSUE TITLE
Snap++ Recording

### ISSUE THREAD

**Issue by moha05** [eni9889/ppsideloader#109]
I have Snap++ and i don't know how to record more than 10 sec Please help

**Comment by marcussssss** [comment]
Go to setting -snap + setting - usage settings- and turn on increase video length and done

**Comment by M202A1** [comment]
Does that actually allow you to upload more than 10 secs?

**Comment by marcussssss** [comment]
Yes

**Comment by turkibatel** [comment]
Zvhmdi
