### ISSUE TITLE
Selfie Lenses on Older Devices? Snapchat++

### ISSUE THREAD

**Issue by JeffResc** [eni9889/ppsideloader#11]
Looking around in the settings, I don't see this... I might just be missing it though... If it isn't possible, could we implement it sort of [like this](http://www.bidnessetc.com/52913-snapchat-selfie-lenses-not-working-on-iphone-4s-iphone-4-and-ipad-heres-the/)?

**Comment by eni9889** [comment]
Please don't post things about the tweaks themselves here. Email support@abcappsllc.com for Snap + support.

**Comment by JeffResc** [comment]
Sorry, I thought this project also worked on it. My bad.
