### ISSUE TITLE
Facebook++ crashes

### ISSUE THREAD

**Issue by sturlei** [eni9889/ppsideloader#111]
So basically when I install snapchat with the preloader everything works just fine. I get the snapchat++ and all features works. When I install Facebook it runs and immediately crashes. I tried with different versions but its still the same. Crashes every single time no matter what I do. I know a lot of people have the same issue. But I wonder if someone has a solution for that?

**Comment by bigpearl28** [comment]
Same for me

**Comment by saud978** [comment]
Me too, I get this error message
"dyld: Library not loaded: /usr/lib/libuasharedanaltyics.dylib
  Referenced from: /var/containers/Bundle/Application/453B9A46-1BBC-42EF-88C4-A14E4C42F7D0/ppsideloader.app/pptweak.dylib
  Reason: image not found"

**Comment by crisdavid7341** [comment]
I'm getting the same error message as saud978

**Comment by sturlei** [comment]
Well, i'm sure about one thing, it is not the app that makes the crash. It's the tweak.  I guess he has to correct this on his server.  Because it crashes on every single version of Facebook!
