### ISSUE TITLE
 Stuck at ppsideloader / Running 1 of 1 custom shell scripts

### ISSUE THREAD

**Issue by sezief** [eni9889/ppsideloader#115]
ppsideloader stuck at Running 1 of 1 custom shell scripts with no error 
i reinstalled the Xcode running 7.3.1 but same problem 
i also install fresh copy of ox alcapitan

**Comment by Jaff22** [comment]
This step has taken me a solid 20-30 minutes before, just give it it's time.

**Comment by saud978** [comment]
This is normal, I had the same issue but then I realize the the building phase is downloading the libraries from the internet (approx 30MB or more) which in slow internet connection takes long time.
