### ISSUE TITLE
Snapchat++ crashing

### ISSUE THREAD

**Issue by onodelta** [eni9889/ppsideloader#116]
Snapchat++ crashes when trying to view stories or any snaps from friends, it will crash for about 10 times over and over and then it will work again for a little while and then it repeats this process.

**Comment by alghamdid** [comment]
Cvhhhh

**Comment by crisdavid7341** [comment]
Try deleting the app, use a new unencrypted snapchat app, and build using the xcode file but stop once it's installed, then re open snapchat to proceed. I'm on the latest snapchat and it runs fine on mine (aside from certain features being broken due to the latest snapchat updates..

**Comment by onodelta** [comment]
I downloaded snapchat from iphonecake.com and then ppsideloader from GitHub and put snapchat as app.ipa into ppsideloader and replaced it and built the app in Xcode and installed on my phone
