### ISSUE TITLE
How to have more than two copies??

### ISSUE THREAD

**Issue by totti1914** [eni9889/ppsideloader#119]
Is there away of having like 3 whatsapp or snapshot or whatever thanx

**Comment by Jaff22** [comment]
Maybe if you speak English I can try to figure out what in the name of HELL you're asking.

**Comment by davidpscne** [comment]
Why would you have 3 same apps on phone? For different profiles?

**Comment by iAboch** [comment]
Try to find out about " iOS app singer " on youtube .. You will see more tutorials
