### ISSUE TITLE
watchkit

### ISSUE THREAD

**Issue by bigpearl28** [eni9889/ppsideloader#12]
i keep getting "This app contains a WatchKit app with an invalid bundle identifier. The bundle identifier of a WatchKit app must have a prefix consisting of the companion app's bundle identifier, followed by a '.'.

**Comment by eni9889** [comment]
Which IPA are you trying to install and what version?

**Comment by bigpearl28** [comment]
Instagram [Instagram Inc.] (v7.20.0 v27257898 os70)-@telefonbuch.rc330_902.ipa

**Comment by bigpearl28** [comment]
Instagram [Instagram Inc.] (v7.20.0 v27257898 os70)-@telefonbuch.rc330_902

**Comment by bigpearl28** [comment]
v7.20.0

**Comment by bigpearl28** [comment]
i tried it again after changing provisioning profile to automatic ,and restating Xcode and it worked
