### ISSUE TITLE
App needs to be verified

### ISSUE THREAD

**Issue by reesz** [eni9889/ppsideloader#122]
So I don't know the exact words for the english error message. But basically after sideloading the app onto my iPhone after months of problemless use it says something along the lines:
"This app needs to be verified before it can be launched." 

So I went to the device-settings on my iPhone (where you need to accept apps from your developer account) and tried to verify it. But it keeps saying I have no internet connection to do this - what I have.

So trying different IPAs as well, it won't let me open the app (not crashing).
Has anybody experienced something similar?

**Comment by Jaff22** [comment]
You speak English better than most fluent people... Is your date and time in sync with the real date and time for your region?

**Comment by reesz** [comment]
Yes it is. And everything worked fine before today, I just did the weekly "fix issue & resign"-routine in XCode, when the App suddenly needed to be "verified". This was never the case before.

**Comment by Jaff22** [comment]
Did you switch Apple IDs?

**Comment by reesz** [comment]
I just had another Apple ID logged into my AppStore for a few moments, but already relogged to my main one, which is also selected in XCode. Could this be the problem?

**Comment by Jaff22** [comment]
I would make a new certificate and make sure it's connected to the original ID.

**Comment by gqqpp** [comment]
@reesz reset all settings on your iOS device and check the date and time
