### ISSUE TITLE
Pokemon Go Crashes

### ISSUE THREAD

**Issue by M202A1** [eni9889/ppsideloader#125]
Hi.

It keeps crashing overtime it tries to load. (Just like Facebook)

Cheers

**Comment by fmierzwa** [comment]
You're most probably using an encrypted IPA file. You can't use the one downloaded from iTunes, use this one instead: https://www.iphonecake.com/app_1094591345_.html

Follow the instruction and it should work. I've tested it successfully on a iPhone 6 with iOS 9.3.2 and XCode 7.3.1
