### ISSUE TITLE
Pokemon Go only walks north

### ISSUE THREAD

**Issue by crisdavid7341** [eni9889/ppsideloader#129]
Pokemon GO doesn't walk the intended path I wish it to follow most of the time; while rarely now it walks in the direction I want it to. It'll instead walk only north regardless where I tap it/what direction I tap it to walk.

**Comment by cewong2** [comment]
When using tap to walk make sure you're facing north (compass has north on the top).

The joystick is based off of you are facing north too.

**Comment by crisdavid7341** [comment]
I see now. Thank you for your reply!
