### ISSUE TITLE
uashredtools

### ISSUE THREAD

**Issue by moshie-1** [eni9889/ppsideloader#13]
i get this "ld: warning: directory not found for option '-L/Users/mohammadaljamri/Desktop/ppsideloader-master-2/uasharedtools'" issue after running the package and youtube gets installed on my iPhone.

**Comment by denniszhaolj** [comment]
Yes, I get into this problem as well. If I delete finding uasharedtools, app will be built, but will not able to open, crash at launch.

**Comment by jbperezf** [comment]
I get the same problem, ending in build failed...

**Comment by eni9889** [comment]
Which app is this for?

**Comment by moshie-1** [comment]
Youtube

**Comment by moshie-1** [comment]
The issue got fixed but now the app keeps on crashing when startup eventhough i went through all the steps

**Comment by moshie-1** [comment]
The same thing happens with snapchat

**Comment by Element108** [comment]
Same problem for me. Apps keep crashing on start

**Comment by denniszhaolj** [comment]
Hi, I get it works. Just ignore it, the process will continue.
IMPORTANT: the ipa.app need to be an cracked IPA file.

2016年4月20日星期三，Element108 <notifications@github.com> 写道：

> Same problem for me. Apps keep crashing on start
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/eni9889/ppsideloader/issues/13#issuecomment-212396350>
>


-- 
Send from my iPhone.

**Comment by moshie-1** [comment]
From which website did u download that ipa? I downloaded several other ipa's and ended up as the same issue mentioned above

**Comment by Element108** [comment]
tried a original Facebook ipa from itunes and one from app(ake

**Comment by denniszhaolj** [comment]
I think this will be considered as illegal by developer, could we talk in
private? Just send mail to denniszhaolk # gmail dot com

2016年4月20日星期三，moshie-1 <notifications@github.com> 写道：

> From which website did u download that ipa? I downloaded several other
> ipa's and ended up as the same issue mentioned above
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/eni9889/ppsideloader/issues/13#issuecomment-212397964>
>


-- 
Send from my iPhone.

**Comment by moshie-1** [comment]
fixed the issue, delete iPhone dev account certificates logout of apple id from Xcode and relogin with a brand new apple id and everything worked.

**Comment by michelesingh23** [comment]
can some one help me my snapchat is crashing i did all the steps but it won't open the app

**Comment by Element108** [comment]
@moshie-1 did you use a legit/original .IPA from iTunes?

**Comment by moshie-1** [comment]
@element108 cracked one

**Comment by Element108** [comment]
@moshie-1 ok. i hope it'll work with legit apps :/
