### ISSUE TITLE
Facebook Crashes , Snapchat Hide Live 

### ISSUE THREAD

**Issue by mastermark1983** [eni9889/ppsideloader#131]
Facebook don,t work it crashes latest working version is 57.0
Snapchat: can you update your to hide Live 

Thx Grtz Mark

**Comment by TinusTK** [comment]
yeh im getting errors when installing the latest facebook 60.0, then once installed it crashes upon opening. how do u find the older version ipa of facebook?

**Comment by TinusTK** [comment]
version 57.0 doesnt work for me, so ive tried version 59.0 and it installs with no errors, but crashes everytime.

i get this as an output. what to do? thx

dyld: Library not loaded: /usr/lib/libuasharedanaltyics.dylib
  Referenced from: /var/containers/Bundle/Application/1ED3232A-1319-45DD-AD32-7CC2E3F8CA4D/ppsideloader.app/pptweak.dylib
  Reason: image not found
