### ISSUE TITLE
Snapchat sideload error

### ISSUE THREAD

**Issue by xmrjordyx** [eni9889/ppsideloader#135]
Hi

I get this error in xcode while im trying to sideload snapchat.
![image](https://cloud.githubusercontent.com/assets/20658858/17131411/ad7fef6c-531d-11e6-98c1-e3af99d33ab6.png)

**Comment by Jaff22** [comment]
Find a new IPA

**Comment by xmrjordyx** [comment]
Worker, just find a other IPA

**Comment by raznet777** [comment]
I'm having the same problem. I have tried many other IPA, but the problem still persists. What version are you using of the IPA?

**Comment by xmrjordyx** [comment]
I am using 9.35.0, i tested 9.35.1 but that one didnt work for me. 9.35.0 works for me on a iphone 6 ios 9.3.3. Hopes this info works for you...

**Comment by raznet777** [comment]
Lovely thank you. I managed to get it working with the latest. Turns out, it was my Xcode playing up, not the IPA.
I had to go: 
Product > Clean,
Product > Build,
Then run the code to the iPhone.
