### ISSUE TITLE
Snapchat Live Stories

### ISSUE THREAD

**Issue by neek247** [eni9889/ppsideloader#139]
I am up to date with the latest snapchat (non-jailbroken) and for the last few snapchat updates the **"Hide Live Stories"** will NOT work, I have signed in and out, I have uninstalled and reinstalled but nothing; is there anything Im doing wrong? Can someone help me or guide me into the right direction?
![img_0245](https://cloud.githubusercontent.com/assets/20696042/17201762/dd62c916-5467-11e6-84d9-a08e53cb56b0.PNG)
![img_0246](https://cloud.githubusercontent.com/assets/20696042/17201763/dff1792a-5467-11e6-90d2-002e853e32b3.PNG)

**Comment by crisdavid7341** [comment]
Same problem; gonna have to wait for an update.

**Comment by neek247** [comment]
This has been going on for the last probably 3-5 updates of snapchat..
