### ISSUE TITLE
Warning: The Copy Bundle Resources build phase contains this target's Info.plist file 'Info.plist'.

### ISSUE THREAD

**Issue by jbperezf** [eni9889/ppsideloader#14]
I get this warning and an error that says:
"Command /bin/sh failed with exit code 1" 

ending in "Build Failed"what can I do?

**Comment by eni9889** [comment]
Can you post a screencap of all of your logs?

**Comment by jbperezf** [comment]
![screen shot 2016-04-17 at 12 58 13 pm](https://cloud.githubusercontent.com/assets/18517225/14590750/80a8adc0-04cc-11e6-91d5-06870a629af4.png)

This happens with every app! (snap, youtube, instagram and WA) but i noticed that the iphone developer certificate in keychain says "NOT VALID: this cartificate has an invalid issuer" but i dont know why this would happen if i did download the app from apples website and did the certificate step just as said with my apple id.

**Comment by jbperezf** [comment]
This problem was caused because the ios developer certificate created when using (create) was not valid: "this certificate has an unknown issuer". I solved this by downloading AppleWWDRCA certificate and importing it to my keychain the certificate was valid at this point but the build was still not succesfull. After creating the bundle identifier go to preference tab (account > View details) and press download all. after doing this the build was successful!
