### ISSUE TITLE
Stuck on Code Signing

### ISSUE THREAD

**Issue by davidhjkim10** [eni9889/ppsideloader#147]
Initially, everything was fine and working smoothly. I could install ++tweaks through Xcode but suddenly when I went to install again, I am no longer able to "fix issue" and the following error comes up: Xcode failed to resolve the issue. Check your code signing settings; ensure you have a matching signing certificate and provisioning profile installed; and try again. 
Any ideas? Not sure how to fix this... I've tried reinstalling iOS and deleted and reinstalled Xcode to no avail.

**Comment by cewong2** [comment]
It's probably your signing certificate. Just hit play, Xcode will ask if you would like it to fix issues for you, and usually it will remake the cert for you as well.
