### ISSUE TITLE
cydia vs ppsideloader 

### ISSUE THREAD

**Issue by iRajaie** [eni9889/ppsideloader#148]
Is tweak ++ updates in  Cydia are the same for ppsideloader ?

**Comment by socca1157** [comment]
Would like to know as well. Mainly because I want to sideload InstaBetter.

**Comment by Jaff22** [comment]
They're the same but through Cydia it's permanent. Highly recommend you jailbreak.

**Comment by crisdavid7341** [comment]
I believe Cydia is more updated than ppsideloader from what I read from other users.

**Comment by Jaff22** [comment]
100% better and more updated Cydia is a must.
