### ISSUE TITLE
instagram++ update?

### ISSUE THREAD

**Issue by omermaderer** [eni9889/ppsideloader#149]
instagram++ update with stories downloader? on the sideload verion
thank you

**Comment by ik4ito** [comment]
Works perfectly for me with the new update.

Although the custom feed doesn't work for some reason

**Comment by omermaderer** [comment]
@ik4ito  are you jailbroken? and if not IOS 9 or IOS 10?

**Comment by ik4ito** [comment]
@omermaderer nope not jailbroken.
iOS 9.3.3
