### ISSUE TITLE
PokeGo++ update?

### ISSUE THREAD

**Issue by vynster** [eni9889/ppsideloader#151]
New version was released today for the official app 1.3.0. The current app in buildstore doesn't work anymore :( - any updates coming soon?

**Comment by TinusTK** [comment]
I was very hesitant against jail breaking my iphone. So I always side load the hacked apps. But I decide to jail break and havnt had a problem since with t ++ apps even with the new poke update. Just my suggestion I recommend it. First timetime JB too

**Comment by avielc** [comment]
@eni9889 Hi buddy, turns out the Pokeppsl tweak isn't updated according to cydia.online.
Can it be updated? 
Can you guide us on how to do it ourselves if needed?
