### ISSUE TITLE
Snapchat iOS 10 Beta 7 Issue

### ISSUE THREAD

**Issue by neek247** [eni9889/ppsideloader#156]
I know this is a iOS 10 Beta 7 issue for Snapchat++ but is there a way to bypass it when you get an error to update to the newest snapchat 9.37.1.0 on the ppsideloader with the error **"Unable to read from device"**

**Comment by neek247** [comment]
Anyone?

**Comment by crisdavid7341** [comment]
When are you getting this error?

**Comment by jakobsperry** [comment]
I have been getting this error too. I'm running iOS 10.0.1 it was working perfectly until i updated to the final release of iOS. Is there any way to fix this?

**Comment by jakobsperry** [comment]
If you restart your phone it should work. it did for me
