### ISSUE TITLE
Snapchat 9.38.0 a problem with the Snapchat ++

### ISSUE THREAD

**Issue by NawafMansour** [eni9889/ppsideloader#159]
Snapchat 9.38.0 new update where there is a problem with the Plus

Could Not Connect?
Please check your connection and try again .

**Comment by iosgods411** [comment]
yeah same issue. downloaded the cracked snapchat and did everything like usual and when running it and trying to login same error:
"Could Not Connect
Please check your connection and try again ."

Thought it was me only but good to know it's not.

**Comment by ALIALKT** [comment]
Yes the same problem, the problem of possible tools ++

**Comment by ahmadobi** [comment]
please fix

**Comment by iyadnn** [comment]
Same issue for all people who logout cannot login back
