### ISSUE TITLE
crashing error

### ISSUE THREAD

**Issue by moshie-1** [eni9889/ppsideloader#16]
dyld: Library not loaded: @executable_path/pptweak.dylib
  Referenced from: /var/containers/Bundle/Application/5EB54C2A-9B6B-4AFD-ABFB-3CFE33E21FE4/ppsideloader.app/YouTube
  Reason: no suitable image found.  Did find:
	/var/containers/Bundle/Application/5EB54C2A-9B6B-4AFD-ABFB-3CFE33E21FE4/ppsideloader.app/pptweak.dylib: mmap() errno=1 validating first page of '/var/containers/Bundle/Application/5EB54C2A-9B6B-4AFD-ABFB-3CFE33E21FE4/ppsideloader.app/pptweak.dylib'
	/private/var/containers/Bundle/Application/5EB54C2A-9B6B-4AFD-ABFB-3CFE33E21FE4/ppsideloader.app/pptweak.dylib: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/5EB54C2A-9B6B-4AFD-ABFB-3CFE33E21FE4/ppsideloader.app/pptweak.dylib'

**Comment by eni9889** [comment]
This sounds like an issue with the download of the tweak. Please Re-Run
