### ISSUE TITLE
problem snapchat ++ don't work

### ISSUE THREAD

**Issue by albarak777** [eni9889/ppsideloader#160]
Please solve the problem as soon as the snapchat ++
Await renovation tools
The problem of lack of network connectivity on all the versions

**Comment by ayman9002** [comment]
same problem

**Comment by WAFA-7** [comment]
Please check your connection and try again <<< that's the msg every time I sign in

**Comment by yaweeh123** [comment]
same here ...?

**Comment by yaweeh123** [comment]
what we have to do in this problem :(

**Comment by drmsn** [comment]
Please do something about this problem ...

**Comment by 0531099996** [comment]
Could Not Connect, Please Check your connection and try again.
this is the message we get when installing the Snapchat++, however it is working fine when using the
fresh copy from App Store
any suggestions please

**Comment by yaweeh123** [comment]
i try so many version 9.35 and 9.37 and 9.38 still the same but while im using jailbreak its working good without problem till when we will be stuckon this problem 

i hope to found a way  to fix this 

thx

**Comment by yaweeh123** [comment]
finally i found a way

**Comment by itsryan249** [comment]
@yaweeh123 what was the way???

**Comment by WAFA-7** [comment]
@yaweeh123 save us please -__-

**Comment by graphicseoul** [comment]
@yaweeh123 save us please!!

**Comment by Jackiedk100** [comment]
Just sign up a new account.
Use it for a while. Log out and log in to your old.
