### ISSUE TITLE
i can't log in

### ISSUE THREAD

**Issue by yaweeh123** [eni9889/ppsideloader#166]
still >>>>>>>????? :(

**Comment by yassersy** [comment]
snapshat ++ only has problem when

**Comment by 0531099996** [comment]
how to fix
كيف الطريقه

**Comment by ahmadobi** [comment]
ما حد يعرف شي
الله يكون بالعون

**Comment by crisdavid7341** [comment]
What do you mean you can't log in? Where does it say this? When does it occur exactly?

**Comment by 0531099996** [comment]
3 days back after the release of the new 9.38 version of snap, we updated our snapchat++ 
since then it's not connecting 
you may see my post also and the others
@crisdavid7341
