### ISSUE TITLE
snap++ won't connect and can't log in

### ISSUE THREAD

**Issue by maubaas** [eni9889/ppsideloader#169]
I just sideloaded snapchat++ again like I do every week, but this time it won't connect when I try to sign in. but the normal snapchat does connect, and I can sign in on that one normally.

**Comment by 0531099996** [comment]
even if you try to creat new account with the. new snap++ it will proceed, unfortunately we all have the same issue

**Comment by raznet777** [comment]
Tutorial Video (English)
https://www.youtube.com/watch?v=NZzGXLmz7_g

**Comment by 0531099996** [comment]
this is temporary solution, whenever you log out you'll need to do it again
it will not work
