### ISSUE TITLE
Could Not Connect

### ISSUE THREAD

**Issue by Dangiiwa** [eni9889/ppsideloader#170]

**Comment by n9a5** [comment]
there's temporary issue fix

https://www.youtube.com/watch?v=f3-ORcM5_JM

**Comment by raznet777** [comment]
English version? Or can you please explain it here. :)

**Comment by 0531099996** [comment]
anything new, we need the ppsideloader developers to change the connection string to solve this issue

**Comment by raznet777** [comment]
Tutorial Video (English)
https://www.youtube.com/watch?v=NZzGXLmz7_g
