### ISSUE TITLE
Temp - Fix Snapchat +

### ISSUE THREAD

**Issue by serajh** [eni9889/ppsideloader#171]
You have to make 2 ipa file of snapchat & you have to use iOS App Signer
1- Sign original Snapchat with your bundle name then install it on your iPhone, After that login with your account.
2- Sign sideloaded Snapchat with same bundle name of original Snapchat then install it as update.

It works for me.
Enjoy your Snapchat ++ =)

**Comment by httpproxx** [comment]
I have pc can I use cydia impactor?

**Comment by serajh** [comment]
@httpproxx ; No idea, I'm using MacBook

**Comment by ccman12345678** [comment]
You can't do this on windows... rip

**Comment by naveednoor159** [comment]
are there any videos showing how to do that 
@serajh

**Comment by Jaff22** [comment]
Cydia Impactor? Unrelated, but yes, you don't use a computer when you use the impactor. It is like hitting reset in your phone settings but that breaks when you jailbreak your phone. I would recommend backing up your device before you use the impactor tool though.

**Comment by serajh** [comment]
@naveednoor159  I don't have a video

**Comment by shansdbz** [comment]
serajh@its working snapchat plus new update 9.38.1 ...how to do with app signer..please instructions ???i have app signer,cydia impactor.at all tell me how to do please

**Comment by raznet777** [comment]
@serajh How do I install it to the phone?

**Comment by serajh** [comment]
@shansdbz @raznet777 This is an arabic instruction, Just follow same steps

https://www.youtube.com/watch?v=f3-ORcM5_JM

**Comment by raznet777** [comment]
Tutorial Video (English)
https://www.youtube.com/watch?v=NZzGXLmz7_g

**Comment by lyrix010** [comment]
This worked for me but there is one issue, the notifications don't work anymore. When you recieve a private snap or chat, you don't get notified. @raznet777

**Comment by raznet777** [comment]
@lyrix010 I have the exact same problem. You can see my comment on the video. It's a risk I'm willing to talk!

**Comment by yaweeh123** [comment]
cuz the bundle id is different its not problem its work for me ,, Thx

**Comment by raznet777** [comment]
@yaweeh123 What bundle ID have you used then?

**Comment by serajh** [comment]
@yaweeh123 I think if you download Snapchat from App store then Sign the latest Snap + to same original bundle ID will update the same original Snapchat with Snap +. I'll try it them update you as well

**Comment by naveednoor159** [comment]
how do u get the hacked ipa @serajh

**Comment by r4m1live** [comment]
@naveednoor159 u can download cracked spa from appcack website .. ; )

**Comment by MohammedX** [comment]
can you share the url for the the hacked and original ipa .

**Comment by fa666ot** [comment]
@lyrix010 @raznet777 @yaweeh123 so if i do the tutorial in the video, ill get snap+ back, but without any notifications??

**Comment by r4m1live** [comment]
Fa666ot yes with out notifications but i think its problem now with builde snap its alwas crash now ;)

**Comment by fa666ot** [comment]
@r4m1live @lyrix010 @raznet777 @yaweeh123  so in other words its not worth doing it if it keeps crashing???

**Comment by Barbie90** [comment]
I'm lost 🤦🏼‍♀️ I wouldn't mind Snapchat plus not notifying me, it is the least of my concerns lol can someone help me get passed the internet connection error ?
I actively try to log in but it continues to tell me to check my internet Connection settings... & my internet & wifi work perfectly . Pls 😩😩😩😩
Happy new year everyone ❣ 
May we all have a blessed year ❤🙏🏻🎉
