### ISSUE TITLE
Youtube++ login

### ISSUE THREAD

**Issue by r0verchr0me** [eni9889/ppsideloader#172]
When i patch YouTube app with the ++ tweak and i instal it on my iPad, I can't login to my YouTube account.

**Comment by NawafMansour** [comment]
Type in Bendel 
com.google.ios.youtube

**Comment by iAboch** [comment]
I think if u duplicate it you must signout from orginal app first

**Comment by r0verchr0me** [comment]
I tried sigout from the original app, and even removing it, but it still doesn't work.

I can't use the bundle id com.google.ios.youtube be cause i have a error saying that bundle id is not available

**Comment by NawafMansour** [comment]
Using a tool ios App Signer

**Comment by avielc** [comment]
i have same issue, not sure how you can change the bundleid like that.
