### ISSUE TITLE
problem instagram ++ || snapchat ++ |||| crash don't work

### ISSUE THREAD

**Issue by albarak777** [eni9889/ppsideloader#174]
[ objc[480]: Class MBUAProgressHUD is implemented in both /var/containers/Bundle/Application/0027AD41-4E30-4E42-A523-F6D6370F070D/ppsideloader.app/libuasharedtools.dylib and /var/containers/Bundle/Application/0027AD41-4E30-4E42-A523-F6D6370F070D/ppsideloader.app/pptweak.dylib. One of the two will be used. Which one is undefined.
objc[480]: Class MBBarProgressView is implemented in both /var/containers/Bundle/Application/0027AD41-4E30-4E42-A523-F6D6370F070D/ppsideloader.app/libuasharedtools.dylib and /var/containers/Bundle/Application/0027AD41-4E30-4E42-A523-F6D6370F070D/ppsideloader.app/pptweak.dylib. One of the two will be used. Which one is undefined.
objc[480]: Class PodsDummy_PureLayout is implemented in both /var/containers/Bundle/Application/0027AD41-4E30-4E42-A523-F6D6370F070D/ppsideloader.app/libuasharedtools.dylib and /var/containers/Bundle/Application/0027AD41-4E30-4E42-A523-F6D6370F070D/ppsideloader.app/pptweak.dylib. One of the two will be used. Which one is undefined.
objc[480]: Class PodsDummy_SSKeychain is implemented in both /var/containers/Bundle/Application/0027AD41-4E30-4E42-A523-F6D6370F070D/ppsideloader.app/libuasharedtools.dylib and /var/containers/Bundle/Application/0027AD41-4E30-4E42-A523-F6D6370F070D/ppsideloader.app/pptweak.dylib. One of the two will be used. Which one is undefined.
2016-09-09 00:12:15.569 Instagram[480:72097] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSBundle initWithURL:]: nil URL argument'
**\* First throw call stack:
(0x1830c2db0 0x182727f80 0x1830c2cf8 0x183a21338 0x183a212bc 0x10151b8c0 0x182b0d47c 0x182b0e2c0 0x10151b804 0x10151aec4 0x10151a24c 0x1013bc394 0x1013bc48c 0x1013bc1d0 0x182b0d47c 0x182b0e2c0 0x1013bc1a8 0x1013bd308 0x1013bd7c0 0x1013bd730 0x182b0d47c 0x182b0e2c0 0x1013bd708 0x1013ba8c0 0x1013bada0 0x1013bade0 0x1010d4a98 0x1200d88d8 0x1200d8a78 0x1200d40dc 0x1200d4070 0x1200d3280 0x1200d3334 0x1200c6088 0x1200ca130 0x1200c5044)
libc++abi.dylib: terminating with uncaught exception of type NSException ]

**Comment by 0531099996** [comment]
what is this?

**Comment by r4m1live** [comment]
yes its problem with .plist ( i think we stopped snap+ without JB ) 

ITS BAD NEWS TODAY

**Comment by yacob841** [comment]
I have this same error but my snap works fine. Trying to install Instagram is the issue.
