### ISSUE TITLE
apps++ crash

### ISSUE THREAD

**Issue by kafremhm** [eni9889/ppsideloader#175]
gays when I'm install apps ++
the app direct close 
any one have solution for this problem 
i have an apple dev account

**Comment by serajh** [comment]
Try to update you iPhone, Clear cash and restart. Then Install the Apps ++ again

**Comment by kafremhm** [comment]
im make full format my iphone 6plus
and try
give me same problem

?? 10?/09?/2016? ?????? 4:04 ?? ??? ?Seraj M. Al Houri ?<notifications@github.com<mailto:notifications@github.com>>:


Try to update you iPhone, Clear cash and restart. Then Install the Apps ++ again

-

**Comment by a-h13** [comment]
I have the same problem. Did you find a solution?

**Comment by kafremhm** [comment]
i think  all people will get this error

?? 10?/09?/2016? ?????? 6:27 ?? ??? ?a-h13 ?<notifications@github.com<mailto:notifications@github.com>>:


I have the same problem. Did you find a solution?

-

**Comment by avielc** [comment]
not sure what's the error you're getting, but if you follow the steps manually it works.
you will need to do some tinkering with install_name_tool\instert_dylib and such, but it'll work

**Comment by a-h13** [comment]
Does it works with ios 9.3.5

**Comment by serajh** [comment]
No issue for me on 9.3.3 & 9.3.5

**Comment by bood220** [comment]
i have every app++ crashes but theres no any error log in Xcode how to fix

**Comment by ALIALKT** [comment]
Facebook++ crash

**Comment by r4m1live** [comment]
All apps crashed what problems ;)

**Comment by avielc** [comment]
In my experience i checked the logs to find there was a wrong link in the exec file of the app that caused it to crash.
i suggest you do the same.
xcode - devices - select your iphone - view logs and check according to the app you installed.

**Comment by a-h13** [comment]
Does any one solve it ?

**Comment by avielc** [comment]
@a-h13 like i said, check the log file on xcode you will see what it fails on.
I noticed either the ppsideloader project adds a link to @executable_path/jailbreak file which doesn't exist.
or some other dylibs aren't linked properly.
its one of these two that causes the crash.

check that please.

**Comment by kafremhm** [comment]
there is no error showing in xcode
install complet
after all app s ++
crashed
cant open

?? 11?/09?/2016? ?????? 5:11 ?? ??? ?avielc ?<notifications@github.com<mailto:notifications@github.com>>:


@a-h13<https://github.com/a-h13> like i said, check the log file on xcode you will see what it fails on.
I noticed either the ppsideloader project adds a link to @executable_path/jailbreak file which doesn't exist.
or some other dylibs aren't linked properly.
its one of these two that causes the crash.

check that please.

-

**Comment by a-h13** [comment]
I know you said I should check the log file, but the problem is that I am not an expert even if I checked it , I will not know the error when I see it

**Comment by avielc** [comment]
Sorry @kafremhm @a-h13 
I wasn't clear on which log to look at.
You can read the device crash reports on xcode using the "Devices" menu.
connect your device, open "devices" on xcode, 
navigate to your device and look up the app that crashed with the relevant time it crashed.
the report should mention the reason it crashed under "Termination Description"

let me know if you still can't find it.

**Comment by a-h13** [comment]
I still can't find the error . I  get an error formulating crash report

**Comment by a-h13** [comment]
Does any one has a working copy  of the ppsideloader ? Please send it to me . I do not know how to fix mine. Also I do not know what is wrong

**Comment by a-h13** [comment]
I think I found the problem causeing the ++app to crash . My problem is that when I creat new bundle , it is not regesterd . So I need help how to solve it.

**Comment by avielc** [comment]
Do you see any error to why it's not registered?

**Comment by a-h13** [comment]
No I just tryed an old bundle and it works but when I tried a new one it is not working
