### ISSUE TITLE
App++ are crashing

### ISSUE THREAD

**Issue by Ruvici** [eni9889/ppsideloader#178]
hey there hope y'all having a good time..
i've been using the ppsideloader for the past few months and it was going okay until the past two weeks snap++ is crashing also youtube++ and instagram++ they only pass are working well with me are whatsapp++ and twitter++. i have two developer accounts and two different MacBooks and its all the same apss crashing after install.

**Comment by likenew** [comment]
all apps++ crash :(

**Comment by serajh** [comment]
Try to signe a hacked app to your certificate & signe ++ app as well to the same bundle ID. Install the signed hacked app, Open it. Then do an update for signed ++ app. It works for me

**Comment by mycoolbrah** [comment]
@serajh can you explain more please? iv never used the iOS app signer
