### ISSUE TITLE
Logging in different account issue.

### ISSUE THREAD

**Issue by iosgods411** [eni9889/ppsideloader#180]
The check your internet connection seemed to be fixed for the first account that you first login to snapchat..but when you logout and try to login another account it doesn't work, says to check internet connection. It lets me log back in to the fist account I logged in without any problems even after logging out but won't let me log in any other accounts. Is anyone else experiencing this issue..any fix or workaround? This sucks because I paid for the premium features. Hope it gets fixed.

**Comment by 0531099996** [comment]
try this steps
- creat new faked account, it should sign in
- toggle some menu and take snap and upload it 
- all of this process should take approximate 5 min.
-log out of the faked account and sign in with your associated e-mail address to your snapchat account 
-everything should be fine.

best wishes
