### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by neek247** [eni9889/ppsideloader#182]
The Snapchat 9.39.0 keeps crashing when I install it via ppsideloader, it installs but will not open and crashes with this is the coding **"libc++abi.dylib: terminating with uncaught exception of type NSException"**

I'm on iOS 10 and have tried 9.39.0 snapchat, I was perviously on 9.38.0 before updating and now its just crashing and will not work. Anyone else with this issue?

**Comment by iosgods411** [comment]
Yeah same. And it sucks because some of us paid for the premium or donated and we can't get support or help.

**Comment by neek247** [comment]
I downgraded, it works now but not with the newest updated snapchat.

**Comment by ajhen16** [comment]
anyone know how to have notifcations working properly with snap ++ on ios 10?

**Comment by mycoolbrah** [comment]
update to newest Xcode 8 version, i was having the same problem. Make sure you're on iOS 10.0.1 too. I got snapchat 9.39.0 working now, as well as Youtube 11.35.8 (newest). Can't get insta or Facebook working tho..
