### ISSUE TITLE
ppsideloader won't go on to iPhone 7?

### ISSUE THREAD

**Issue by DecMurray** [eni9889/ppsideloader#185]
Was working fine on iPhone 6S but now won't install to iPhone 7. Anyone else having this issue?

**Comment by bigpearl28** [comment]
i got snapchat, twitter and youtube working on mines ...but instagram and Facebook crashes

**Comment by EARoa** [comment]
Mine worked just fine. make sure you have the latest version

**Comment by crisdavid7341** [comment]
I was able to build, run, and install everything but Facebook back onto my iPhone 7 (Youtube, and WhatsApp are the only ones I don't use). I noticed that it's been difficult to add ipas that I then sign under myself.
