### ISSUE TITLE
Enable file sharing on original app

### ISSUE THREAD

**Issue by tgraeber** [eni9889/ppsideloader#188]
I have an old app from 2012 that's no longer available on the App Store (but I own a copy & it's in my iTunes account & running on my iPhone 6. I know how to add enable file sharing through ppsideloader on a 2nd copy (using the .ipa file) but how can I change file sharing on the original app (running on my phone) in order to access ALL my current data? HELP!

**Comment by kmddd59** [comment]
If you find this one out contact me on twitter @wtfarris or dm me here on GitHub
