### ISSUE TITLE
Tap to advance Stories not working

### ISSUE THREAD

**Issue by onemoregenius** [eni9889/ppsideloader#189]
I can hit View on a received snap, but cannot tap to advance a Story. If I start a Story I have to force close the app to navigate to anything else. 

iPhone 6S/iOS 10.0/Xcode 8/Snapchat version 9.39.3.0

**Comment by bandr0099** [comment]
What's the solution

**Comment by onemoregenius** [comment]
So far, the solution is to wait for Cokepokes to come out with his dylib to sideload since there's. even no answer here.
