### ISSUE TITLE
Could Not Connect problem occurring again.

### ISSUE THREAD

**Issue by iosgods411** [eni9889/ppsideloader#191]
Please check your connection and try again error occurring after updating to the latest snapchat and after redownloading the latest updated ppsideloader with the updated pptweaks. The previous version of snapchat works fine and connects just this one doesn't. Fix soon?

**Comment by neek247** [comment]
Same for me, with the last 2 versions..

**Comment by serajh** [comment]
Try capitalizing the first letter of your username. Worked for me!
