### ISSUE TITLE
Snapchat Connect Issue

### ISSUE THREAD

**Issue by neek247** [eni9889/ppsideloader#194]
I installed the latest snapchat via ppsideloader but when I sign-in and it wants the code I put it in and it says **"Could not connect. Please try again later."** Is this a fixable issue or just wait until the next update? This happens with the version previous to this also, so is there a fix?

**Comment by serajh** [comment]
Try capitalizing the first letter of your username. Worked for me!

**Comment by raznet777** [comment]
If i don't put the capital, it immediately says no connection. However, if I put the capital, it takes me to the 6 digit code sign in, and says 'Could not connect' there instead.

**Comment by onodelta** [comment]
hey I had the same exact issue when I tried to log in with my username, I decided to try to log in with my email instead of username and it worked!! This was so annoying, give it a shot.

**Comment by raznet777** [comment]
Thank you so much! You are an absolute star!!!

**Comment by neek247** [comment]
Tried the caps and nothing still no connection, also tried my email with and without a cap and nothing.

**Comment by fa666ot** [comment]
lol same

**Comment by fa666ot** [comment]
did anybody find a fix for this????
