### ISSUE TITLE
Snapchat Check your connection issue when logging into multiple accounts.

### ISSUE THREAD

**Issue by iosgods411** [eni9889/ppsideloader#195]
I am getting that annoying error message where it tells you to check your connection and it couldn't log you in. It happened in the past and they managed to fix it. It lets me login one account ( the account I first logged in with upon side loading) any other account I try to login after that it gives the check your connection error. Please fix this, this happened previously and you guys managed to fix it.

**Comment by serajh** [comment]
Try capitalizing the first letter of your username. Worked for me!
