### ISSUE TITLE
Snapchat blocked/Deleted account 

### ISSUE THREAD

**Issue by akshaypatil4321** [eni9889/ppsideloader#197]
Snapchat blocked my account after installing Snapchat++. Now when I try to log in it says account with this username can't be find. Please improve the security of snapchat++.

**Comment by crisdavid7341** [comment]
Follow this if you wish to use the ++ feature safely again on a new snapchat account https://github.com/eni9889/ppsideloader/issues/198

**Comment by akshaypatil4321** [comment]
@crisdavid7341 
Basically I tried snapchat++ with 2 versions of snapchat which are 9.40 and 9.37 on iOS 10. And guess what both accounts are deleted by snapchat.

**Comment by crisdavid7341** [comment]
Are you using a free account, or a developer account to perform the sideloading of snapchat?

**Comment by eraserdude** [comment]
@akshaypatil4321 Can you elaborate on this? Were you just using snap+ normally? Have you resolved this issue or is your account still deleted?

**Comment by akshaypatil4321** [comment]
Yup. Snap+ normally. And after using it for like 1-2 days I got message showing up that when I tried to log in "We cannot find account with this username". And after contacted to snapchat, they told me that This account is no more in use because of the security reasons.
