### ISSUE TITLE
Snapchat recognizes logins from hacked apps

### ISSUE THREAD

**Issue by GavinSawyer** [eni9889/ppsideloader#198]
I'm on iOS 10 so I have a double install of Snapchat and Snapchat ++. The original snapchat can easily log in, but when i log in with Snapchat ++, it says it can't connect to the internet. I logged into Snapchat within like a minute from attempting to log into Snapchat ++, so I see this as an issue of the app recognizing logins from hacked clients. This is dangerous, as Snapchat may even delete hacked accounts! Please improve security.

**Comment by GavinSawyer** [comment]
I have downgraded to 9.39.02 and I can now log in again. I'd also like to suggest that everybody else do this before your account can be tagged as hacked by Snapchat.

**Comment by akshaypatil4321** [comment]
You are right!! Especially Snapchat++ has poor security. I lost my account with 2000 views :( 1 day back ! Snapchat just deleted my account without any notice/email. So I would suggest don't use Snapchat++, instead you can use phantom way more secure than Snapchat++

**Comment by crisdavid7341** [comment]
Is version 9.32.2.0 the highest you can go?

**Comment by GavinSawyer** [comment]
@Crisdavid7341: Not totally sure how Snapchat's versioning works but 9.40 didn't work for me so I downgraded to 9.39.02 and it worked fine. 👍 A lot of other people are saying that their accounts are being deleted so I wouldn't risk a later version. 😬

**Comment by fa666ot** [comment]
@GavinSawyer @akshaypatil4321 i havent had any issues with using snap+ on iOS10 at all, but now im worried hah.. also how do you use phantom without cydia??? i know you have to jailbreak your phone to get cydia, but is there even a jailbreak for iOS10 yet?? or is it now possible to get phantom without cydia??

**Comment by crisdavid7341** [comment]
@fa666ot You'll want to check this out https://github.com/CokePokes/PhantomExo
I tried using this but the instructions were a little confusing, and I couldn't get it working (even with the simple version he provides).

**Comment by fa666ot** [comment]
@crisdavid7341 thanks man!! im definitely gonna try it out tomorrow when i wakeup haha, hopefully it will work/i can understand it

**Comment by crisdavid7341** [comment]
@fa666ot no problem and I have a developer account but the process just didn't work even after following the instructions. When I did get it on my phone; snapchat kept saying I didn't have an internet connection. Just not sure what I'm doing wrong, or if there's extra steps for those with developer accounts.

**Comment by crisdavid7341** [comment]
Anyone know if this issue was fixed? I see Snapchat for ppsideloader was updated recently.

**Comment by akshaypatil4321** [comment]
Basically I tried snapchat++ with 2 versions of snapchat which are 9.40 and 9.37 on iOS 10. And guess what both accounts are deleted by snapchat.

**Comment by crisdavid7341** [comment]
This makes me nervous since it's so far working with 9.37.2 for me ...

**Comment by crisdavid7341** [comment]
Is everyone using a free account, or a developer account to perform the sideloading of snapchat?

**Comment by beBoss** [comment]
No working snapchat anymore? The oldest versions has problem too, show messages like "your vers is too old, upgrade"

**Comment by GavinSawyer** [comment]
YIKES! Got this message from Team Snapchat out of nowhere just now.
![image](https://cloud.githubusercontent.com/assets/6238591/20032457/a4c50072-a360-11e6-9927-862de63785a9.png)

This is a serious issue please boost!
