### ISSUE TITLE
notifications????

### ISSUE THREAD

**Issue by fa666ot** [eni9889/ppsideloader#199]
has the issue of snapchat notifications not showing up been fixed yet??? without the way of "getting around it"??? i havent done that due to not wanting to risk messing anything up.. and if there is a 100% way to do it without having anything mess up on me can anyone fill me in on a good "how to"??

**Comment by davidpscne** [comment]
Its been really long since they stopped working.. i don't know why they don't fix it.. it is really that hard?

**Comment by fa666ot** [comment]
@davidpscne yeah i know its been a while now and im sick of it lol i need a fix

**Comment by crisdavid7341** [comment]
I think the issue is due to the new security of the newer updates to the apps, and or what ever has been changed from iOS 9 to 10. Notifications were working for me on the beta iOS 10 but I think till either beta 4 or 5.

**Comment by SiNaPsEr0x** [comment]
Not working On iOS 10.1.1 with whatsapp tweaked :( fixxxxxx
