### ISSUE TITLE
Snapchat versions above 9.32.2 don't login

### ISSUE THREAD

**Issue by crisdavid7341** [eni9889/ppsideloader#203]
I'm not entirely sure what the highest version number of snapchat that works is. Anything higher than 9.32.2 says that there is basically no internet connection (regardless if on Wifi, or cellular). I can connect to any other account aside from the one I use with ppsideloader.

**Comment by iosgods411** [comment]
Yeah this has been an issue and I have posted on here many times. He hasn't bothered addressing the issue or fixing it yet. I have paid for all his premium ad removals and yet still can't fix it. How shitty.
