### ISSUE TITLE
iOS 10.1 Issue

### ISSUE THREAD

**Issue by neek247** [eni9889/ppsideloader#205]
The app needs to be updated so we can install the latest version of snapchat, the ppsideloader only goes to 10 not 10.1

**Comment by drake90001** [comment]
The app works fine, you have to use the Xcode Beta GM Seed to get iOS 10.1 support.

**Comment by neek247** [comment]
Yah, I figured that out; but now I can get the right updated file for snapchat. It never lets me sign in, I get a connection error.

**Comment by drake90001** [comment]
Login with your email. Disable 2FA if you have it enabled.

**Comment by iosgods411** [comment]
What is 2FA drake? And where do I go to disable it?

**Comment by drake90001** [comment]
2FA is two-factor authentication, and you can disable it in Snapchat settings under Login Verification.

**Comment by fa666ot** [comment]
has there ever been a fix yet for this for iOS10.1??? i still cant log in and ive tried literally everything people have said "worked" for them on this site
