### ISSUE TITLE
Error while tweaking Snapchat

### ISSUE THREAD

**Issue by RubikOfAstora** [eni9889/ppsideloader#206]
Always when i try to Tweak Snapchat i got the following Error:
Unable to launch /private/var/containers/Bundle/Application/CFED503C-8525-4119-B7E7-C71B06883C8F/ppsideloader.app

System: macOS Sierra 10.12
Xcode: Xcode 8.1 Beta GM Seed
Phone: iPhone 6s Plus
IOS 10.1

Tried with Snapchat: 9.10 / 9.32 / 9.42

Did someone know what to do?

**Comment by mycoolbrah** [comment]
Lots of issues with sideloading now, PPsidloader basically needs to be updated as well as snapchat, security is very low... Few work-arounds though, try doing this, im running this, no need for xcode just just cydia impactor and you will endup with a semi-safe snap++. Iv been using on a new account just for caution for 3 days now and no 3rd party message from snapchat as of yet. Use this until phantom is stable and fixed or PPSideloader gets updated and snap++ can be safely sideloaded without being detected by snapchat 

Step 1. Delete any versions of sideloaded/Appstore Phantom/Snapchat.
Step 2. Download "Snapchat Sign in" from the link below.
Snapchat Sign in || http://www79.zippyshare.com/v/bO23HZ8w/file.html
Step 3. Install "Snapchat Sign in" whit Cydia Impactor & Login with your account.
Step 4. KILL Snapchat from background.
Step 5. Download & Install "Snapchat++ v9.39.3.0" with Cydia Impactor from the link below.
Snapchat++ v9.39.3.0 || http://www69.zippyshare.com/v/jGnwtZTA/file.html
Step 6. ENJOY THIS TEMPORARY FIX!!!

*** Note || Tested & WORKING in iPhone 7Plus Running iOS 10.1.1 ***
