### ISSUE TITLE
Snapchat++ 9.42.1 Auto Logout

### ISSUE THREAD

**Issue by raznet777** [eni9889/ppsideloader#209]
For some reason, after installing the latest version of snapchat++, I will login and 3 seconds later the app will automatically log me out, forcing me to log in again, then it will kick me out. It just goes round in circles. Any ideas?

**Comment by r4m1live** [comment]
I'm too , try to login at ur snap with Email , first capital like this Snap@live.com 
its work with me at now

**Comment by raznet777** [comment]
Unfortunately that did not work. Thank you for the suggestion though!

**Comment by r4m1live** [comment]
It's work with me I'm now use snap+

**Comment by raznet777** [comment]
How did you install snap+?

**Comment by raznet777** [comment]
UPDATE: I have managed to get snapchat++ fully installed, just don't get notifications anymore :(

**Comment by ccalmdownn** [comment]
How did you get it? If you don't mind me asking

**Comment by neek247** [comment]
Yes, same here; please tell us how to fix it because its annoying.

**Comment by kakaswr22** [comment]
download latest snapchat++ and try login but make sure put capital litter for you username....if still didn't work leave it for half an hour then try 
mine worked like that any question or want latest snapchat++ ipa 
follow me on twitter @kakaswr22

**Comment by neek247** [comment]
nope not working still

**Comment by ccalmdownn** [comment]
Did you try to login using your email instead? & if yes did it work? Cause I'm too lazy to try it atm lol

**Comment by ali1989vip** [comment]
The problem was repaired snapchat: Install the new version approved by snapchat and then install the issuing snapchat 9.39.3

**Comment by ccalmdownn** [comment]
Links please? I would really appreciate it

**Comment by neek247** [comment]
so over-write the file or delete it and then install the hacked version? I use xcode

**Comment by mycoolbrah** [comment]
Follow these steps and you should get it working. I'm currently running on iphone 6s ios 10.1

1. Snapchat Sign in:
http://www79.zippyshare.com/v/bO23HZ8w/file.html
2. Install and log in
4. KILL Snapchat from background. Don't delete the app! 
5. Download and install Snapchat++ v9.39.3.0 with Cydia Impactor
Snapchat++ v9.39.3.0 || http://www69.zippyshare.com/v/jGnwtZTA/file.html
