### ISSUE TITLE
fix snapchat+ 9.42 

### ISSUE THREAD

**Issue by ali1989vip** [eni9889/ppsideloader#210]
The problem was repaired snapchat: Install the new version approved by snapchat and then install the issuing snapchat 9.39.3

**Comment by Legitgamer264** [comment]
Can you link me the 9.39.3 ipa?

**Comment by ali1989vip** [comment]
https://dailyuploads.net/tnl26ai8sg44

**Comment by Legitgamer264** [comment]
Will I have to overwrite the original? I don't use cydia impactor. I use ipastore

**Comment by eraserdude** [comment]
Thank you this worked for me

**Comment by al-muftah** [comment]
dose not work for me :( I am running iOS 9.3.5

**Comment by ccalmdownn** [comment]
I installed the sign in snapchat latest version then signed in & installed snapchat 9.39.3 & still got the normal snapchat? I don't understand

**Comment by mycoolbrah** [comment]
@ccalmdownn 

Use these through imapctor
1. Snapchat Sign in:
http://www79.zippyshare.com/v/bO23HZ8w/file.html
2. Install and log in
4. KILL Snapchat from background. Don't delete the app! 
5. Download and install Snapchat++ v9.39.3.0 with Cydia Impactor 
Snapchat++ v9.39.3.0 || http://www69.zippyshare.com/v/jGnwtZTA/file.html
