### ISSUE TITLE
*Not Issue* [Snapchat++ v9.39.3.0] Temporary Fix "Auto-logout" / Alternative for Snapchat Phantom!

### ISSUE THREAD

**Issue by Abbasoo** [eni9889/ppsideloader#211]
Step 1. Delete any versions of sideloaded/Appstore Phantom/Snapchat.
Step 2. Download "Snapchat Sign in" from the link below.
Snapchat Sign in || http://www79.zippyshare.com/v/bO23HZ8w/file.html
Step 3. Install "Snapchat Sign in" whit Cydia Impactor & Login with your account.
Step 4. KILL Snapchat from background.
Step 5. Download & Install "Snapchat++ v9.39.3.0" with Cydia Impactor from the link below.
Snapchat++ v9.39.3.0 || http://www69.zippyshare.com/v/jGnwtZTA/file.html
Step 6. ENJOY THIS TEMPORARY FIX!!!

*** Note || Tested & WORKING in iPhone 7Plus Running iOS 10.1.1 ***

**Comment by mycoolbrah** [comment]
can confirm, this works. iphone 6s ios 10.1

**Comment by EARoa** [comment]
Logged me out instantly :/

**Comment by Jaff22** [comment]
Cydia Impactor on iOS 10? Is there a jailbreak I'm unaware of?

**Comment by wasif09** [comment]
do not use snapchat detects this tweak and they terminate your account

**Comment by Abbasoo** [comment]
@Jaff22 http://www.cydiaimpactor.com/
