### ISSUE TITLE
Should I be worried?

### ISSUE THREAD

**Issue by JMccormick264** [eni9889/ppsideloader#212]
I got this today![](http://i.imgur.com/044HAT9.jpg) 
Should I be worried?

**Comment by crisdavid7341** [comment]
I've yet to encounter this (I hope not anytime soon) I'd steer clear of using sideload for the moment if this is really a legit snapchat account.

**Comment by Legitgamer264** [comment]
It was from the Team Snapchat username. It's from a legit account

**Comment by dale455** [comment]
I got the same message and now a temporary ban.

**Comment by Jaff22** [comment]
Stop sideloading, get a jailbreak. I've had no problems with ++ thru Cydia.

**Comment by Legitgamer264** [comment]
@Jaff22, I'm on iOS 10 probably like everyone else who is commenting. So we can't get a jailbreak lol

**Comment by eraserdude** [comment]
@Jaff22 I'm jailbroken using Phantom and I got the message too

**Comment by mycoolbrah** [comment]
I wouldn't be worried, looks like most people using both phantom and/or ++ got this. Do what coke pokes recommends and email snapchat through their website (report issue, go through options until you find "my issue is not listed" or something) and  tell them you are seeing it as a mistake.

**Comment by wasif09** [comment]
yes you should delete  got blocked for over 12 hours
