### ISSUE TITLE
WhatsApp++ restore Cloud Backup problems

### ISSUE THREAD

**Issue by unityhd** [eni9889/ppsideloader#213]
Hi,
have anyone a method to change the AppStore WhatsApp with the WhatsApp++ Version with the chance to restore the WhatsApp Cloud Backup ?

If i delete the AppStore App and start WhatsApp++ there is no Cloud Backup, but when i install the AppStore Version back it directly find the Cloud Backup.

Versions are the same 2.16.16.

**Comment by borkanOman** [comment]
Is this whatsapp 2?
