### ISSUE TITLE
Snapchat ++ 9.43.0 || Can't log in

### ISSUE THREAD

**Issue by ochitsuita** [eni9889/ppsideloader#217]
i've been doing this hack for a while and recently i had to redo it and when i did it, i got the issue of not being able to log in, i keep getting the error of "could not connect, please check your internet connection and try again" allthough my connection is working totally fine and works great without the hack. Is there a fix? please.

**Comment by crisdavid7341** [comment]
Do you have two factor authentication enabled on your snapchat account?

**Comment by ochitsuita** [comment]
no i do not

**Comment by crisdavid7341** [comment]
I know version 9.39.2.0 works I believe

**Comment by beBoss** [comment]
Nope, it's not working!

**Comment by crisdavid7341** [comment]
I guess well be needing to compromise with Phantom for now.
