### ISSUE TITLE
Youtube++ bugs

### ISSUE THREAD

**Issue by HugaShire** [eni9889/ppsideloader#219]
+[blank] Seconds add/minuses 50000+ seconds

**Comment by Legitgamer264** [comment]
I can't login either. You aren't alone

**Comment by HugaShire** [comment]
fixed the login

**Comment by HugaShire** [comment]
seconds still broken

**Comment by Legitgamer264** [comment]
How did you fix the login?

**Comment by HugaShire** [comment]
it just actually worked idk

**Comment by HugaShire** [comment]
try ipahub on reddit
