### ISSUE TITLE
SNAPCHAT++ iOS10.1 // CANNOT LOG IN !!!

### ISSUE THREAD

**Issue by fa666ot** [eni9889/ppsideloader#220]
ive tried literally every type of "fix" that people have said apparently "worked" for them on this site, and i still cant log in to snapchat++ anymore x__x... has this ever been actually fixed yet D; or is there a fix coming soon??? anything that i dont know of that wasnt mentioned on the site???? please help

**Comment by crisdavid7341** [comment]
I've been using the old version 37 or something since updating snapchat was causing login issues

**Comment by fa666ot** [comment]
what version is it exactly that is working for you ;o ??

**Comment by beBoss** [comment]
There is no working version, the old ones shows error that they are outdated the new ones shows that you have problem with the internet connections so, same shit...

**Comment by fa666ot** [comment]
fuckkkkk D; someone needs to fix this shit and make an update or somethinggg x__x

**Comment by crisdavid7341** [comment]
I believe version 9.39.2.0 works. Not trying to jinx my luck but I haven't gotten any errors or messages with snapchat being old.

**Comment by beBoss** [comment]
Will test it but I am sure that is not working, will text back when I am sure.

**Comment by beBoss** [comment]
Nope, it is not working!

Message:

Oops!
You're using a ver of snapchat or OS that's not longer supported. Please upgrade your device's os and upgrade to the newest app ver to use snapchat. Thanks!

**Comment by crisdavid7341** [comment]
What iOS version are you running? I'm on 10.1.1

**Comment by beBoss** [comment]
10.2(14C5077b)

**Comment by fa666ot** [comment]
arghhh someone needs to find a legitimate fix for this x__x ..OR we just need an overall update asap, ill deadass sell my soul 😫😭😩!!!!!!

**Comment by SimonSCLT** [comment]
@crisdavid7341 Can you share your ipa file of Snap++ 9.39.2.0? I would like to try on my iPhone running to 10.1.1  : )

Thanks

**Comment by beBoss** [comment]
https://openload.co/f/jt0XF5j27Bg/Snapchat_%5BSnapchat_Inc.%5D_%28v9.39.2_v9.39.2.0_PI_LP_os80%29-Widow.rc334b_902.ipa

**Comment by fa666ot** [comment]
did 9.39.2.0 end up working???

**Comment by beBoss** [comment]
Have you read the comments above?

**Comment by fa666ot** [comment]
obviously??? hense which is why i asked if it worked or not for @SimonSCLT ....lmfao

**Comment by crisdavid7341** [comment]
Mine was working but now I get signed out as of today :/

**Comment by Barbie90** [comment]
Happy new year everyone ❣
Does anyone have a working tweaked Snapchat plus on iOS 10.2 betta version?
If you do, plssss share 🤦🏼‍♀️ 
I haven't been able to get passed the log in 🙄 It continues to tell me to check my internet connection settings which obviously work. 
Or maybe I've done something wrong ? Pls Share I'm open to any suggestions!
I don't have cydia, I don't have jailbreak . 
& I do not use a computer to download tweak apps directly into my iPhone. 
Thanks everyone, have a blessed year ❣❣❣
