### ISSUE TITLE
Library/MobileDevice/Provisioning Profiles/.mobileprovision" for reading: No such file or directory

### ISSUE THREAD

**Issue by sinfulslave** [eni9889/ppsideloader#222]
is there any solution for such problem
thanks

**Comment by Dark-Mind** [comment]
Use 'generic iOS device' instead of 'iOS simulator' as the target device for building

**Comment by sinfulslave** [comment]
i have already fixed this issue now facebook doesn't open is there any image of facebook that works

**Comment by Legitgamer264** [comment]
Here is a one that works from ProTechZone. Facebook version 57.0 https://mega.nz/#!1FcHSYbZ!EQnmxPIC3jnEN80lUOL3veSXo6gA3O1-HUDSMHDJ5NM

**Comment by Legitgamer264** [comment]
Also, here is his site  http://protechzone.weebly.com/tweakedapps.html

**Comment by sinfulslave** [comment]
how to overcome this problem

**Comment by sinfulslave** [comment]
https://i.stack.imgur.com/tHqUy.png

**Comment by sinfulslave** [comment]
ok tried it didn't work also it crashes

**Comment by bao3** [comment]
@sinfulslave  It's not a problem ,just plugin your iphone/ipad ,select "generic iOS Device", then this would be fixed .

**Comment by bao3** [comment]
@Dark-Mind  Thank you , it worked ! Big thanks
