### ISSUE TITLE
whenever i install cracked ++app it opens and closes quickly

### ISSUE THREAD

**Issue by sinfulslave** [eni9889/ppsideloader#223]
iam using virtual machine osx  11.12  Sierra
is there anyway to make it run i have tried be4 but it didn't do anything please is there any solution for such problem

**Comment by Legitgamer264** [comment]
What app? If it's Facebook then everyone Is having that issue if they use ppsideloader

**Comment by sinfulslave** [comment]
yes i don't need other apps i only use facebook++ 
so what is the solution and why facebook instead of all other apps 
and is there ipa that works? am currently using ios 10 but i have ipad with 9.3.5

**Comment by Legitgamer264** [comment]
It's because the ++ tweak hasn't been updated to work with the latest Facebook. The one I'm using download and installed through ipastore is version 64. I think version 64 works with the latest ++ tweak

**Comment by sinfulslave** [comment]
i have tried many versions 68 54 50 45 61 nothing happened although youtube worked from the first time

**Comment by sinfulslave** [comment]
what is the current fb version u use plus plus on and what is your ios version?

**Comment by beBoss** [comment]
Can you tell me which youtube version works for you. And yeah most of the app aren't tested and debugged to be fixed for sideloading and that's why they don't work. The author doesn't update the script and maybe that's the reason some apps are crushing.
