### ISSUE TITLE
Snapchat++ .. no internet issues + logout any solution 

### ISSUE THREAD

**Issue by r4m1live** [eni9889/ppsideloader#225]
i was use 9.39.3 it was work until today .. what is problem : )

**Comment by ccalmdownn** [comment]
Same & then I tried 38, 37.2, & 35 versions & still the same problem it keeps logging me out :(

**Comment by crisdavid7341** [comment]
Same problem here with me. I tried rebuilding the app and it worked for another day but just got logged out. Even the notification workaround was patched in the last few Snapchat updates

**Comment by Nameless2b** [comment]
https://twitter.com/snapchatsupport/status/807392684641951744

**Comment by crisdavid7341** [comment]
I recently read that Snapchat was getting version number information whenever a user updated the app. Once they saw that their device could run the latest version of Snapchat; they mark your account, and you can no longer downgrade to an older version of Snapchat. Had you not updated, or had auto update for the official Snapchat you won't be affect. I believe this is another reason people cannot successfully use this side loading method. They're cracking down hard on anyhthing that is not apart of the official Snapchat application.

**Comment by Viral12** [comment]
any new updates on Snapchat++ I need it! where can I download a working version?

**Comment by r4m1live** [comment]
i try with dylib but no chance at now : )
