### ISSUE TITLE
RIP snapchat ++

### ISSUE THREAD

**Issue by ccalmdownn** [eni9889/ppsideloader#226]
Anyone know how can I get snapchat++ back, I just need it so bad man 😭

**Comment by crisdavid7341** [comment]
Just get all your friends to use Instagram. Honestly if all my friends used Instagram; I would just delete Snapchat, and use Instagram ++. They really aren't against third party apps like Snapchat.

**Comment by Legitgamer264** [comment]
@crisdavid7341 I use Instagram++ more often. If you want the latest, I can link you. I compiled it today

**Comment by crisdavid7341** [comment]
I use Instagram ++ on the latest version. Just Snapchat ++ recently failed on me like everyone else. @Legitgamer264
