### ISSUE TITLE
Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by MpDesigns** [eni9889/ppsideloader#23]
When I try to build the App (tried it with Snapchat and Youtube) xCode gives me this error.

**Comment by eni9889** [comment]
Do you have any screenshots?

**Comment by MpDesigns** [comment]
(https://cloud.githubusercontent.com/assets/9025924/14763749/ae3c5818-099f-11e6-9eb4-6d86ff400d8c.png)

**Comment by matheuztavarez** [comment]
same problem

**Comment by espilsad** [comment]
In your target you have to go to Build phases -> Run Script -> Run script only when installing
<img width="888" alt="run script" src="https://cloud.githubusercontent.com/assets/17473295/14861521/e4e526fe-0cad-11e6-97a5-8d71098c9d4a.png">

**Comment by MpDesigns** [comment]
Thank you. It worked!
