### ISSUE TITLE
ppsideloader-master/script/modify_app: Permission denied

### ISSUE THREAD

**Issue by AhrimanSefid** [eni9889/ppsideloader#233]
Hi All.
Why?

/Xcode/DerivedData/ppsideloader-gveuwkgwwnkhxqcoucswewtrfdad/Build/Intermediates/ppsideloader.build/Debug-iphonesimulator/ppsideloader.build/Script-473D787B1CBAEAA600BA76CD.sh: line 2: /Users/ahrimansefid/Desktop/Share/ppsideloader-master/ppsideloader-master/script/modify_app: Permission denied

Showing Recent Issues
/Xcode/DerivedData/ppsideloader-gveuwkgwwnkhxqcoucswewtrfdad/Build/Intermediates/ppsideloader.build/Debug-iphonesimulator/ppsideloader.build/Script-473D787B1CBAEAA600BA76CD.sh: line 2: /Users/ahrimansefid/Desktop/Share/ppsideloader-master/ppsideloader-master/script/modify_app: Permission denied

**Comment by iYsood** [comment]
I think you need to disable System Integrity Protection.

to do this, 
1. Reboot the Mac and hold down Command + R keys simultaneously after you hear the startup chime, this will boot OS X into Recovery Mode.

2. When the “OS X Utilities” screen appears, pull down the ‘Utilities’ menu at the top of the screen instead, and choose “Terminal”

3. Type the following command into the terminal then hit return:
csrutil disable; reboot

4. You’ll see a message saying that System Integrity Protection has been disabled and the Mac needs to restart for changes to take effect, and the Mac will then reboot itself automatically, just let it boot up as normal.

**Comment by crisdavid7341** [comment]
I've disable this but still having a problem
