### ISSUE TITLE
How build ppsideloader project from terminal

### ISSUE THREAD

**Issue by vohulg** [eni9889/ppsideloader#235]
I need build ppsideloader project not from xcode and from terminal, for example with utilite "xrun". 

I try so:  '**xcodebuild -project  ./ppsideloader.xcodeproj -target ppsideloader**' but get so error:

'Check dependencies
No profiles for 'com.myprofile' were found:  Xcode couldn't find a provisioning profile matching 'com.vohulg'.
Warning: The Copy Bundle Resources build phase contains this target's Info.plist file 'Info.plist'.
Code signing is required for product type 'Application' in SDK 'iOS 10.2'

** BUILD FAILED **'

How right make command line for building ppsideloader project ? 

Thanks!

**Comment by HugaShire** [comment]
Lol I wish this can happen on windows
