### ISSUE TITLE
YouTube++ still getting ads after paying to remove them

### ISSUE THREAD

**Issue by Roverjacobs** [eni9889/ppsideloader#237]
Paid 2$ to remove all the ads but nothing change and after 4 days of waiting to see if anything would change I have become sick of all the ads so I'm considering a chargeback for not providing the service I paid for. I also sent the developer an email but got no response

**Comment by Jaff22** [comment]
Did you sign in to your account in the app?

**Comment by Roverjacobs** [comment]
Yes I signed into the YouTube++ portion of the app

**Comment by kakaswr22** [comment]
@kakaswr22 https://drive.google.com/open?id=0B2I86wbqDYxAN0NCaGFPU0hGWXc
download that no ads latest youtube version

**Comment by blaskotron** [comment]
That google drive file is missing. I'm also signed in. The directions for modifying the Build ID to  com.google.ios.youtube.noads is not clear as well. Not sure if I've got the right spot, also don't see a remove plugins option.

**Comment by JMccormick264** [comment]
Also check out this https://github.com/JMccormick264/PPAppsIPARepo (mine)

**Comment by kakaswr22** [comment]
link works now but next time when the link is broken thats mean i update it and old one remove

**Comment by blaskotron** [comment]
Thanks, I was using an older version. That is probably why the video ads were still playing. Sideloaded seems to work fine.
