### ISSUE TITLE
YouTube links in Safari won't open in YouTube++

### ISSUE THREAD

**Issue by briankendall** [eni9889/ppsideloader#241]
I've installed YouTube++ both via sideloading and using the method detailed on the read me page of this GitHub project. But no matter what I do, when I open a YouTube page in Safari, it just opens as a webpage in Safari rather than opening YouTube++ like what happens when the official YouTube app is installed via the app store.

I can get the page to open in YouTube++ by editing Safari's URL and manually changing the URL scheme from https:// to youtube://. But that's pretty annoying, and it'd be great if it could work like it does for the official YouTube app.

Is there any way to get that to work?

**Comment by HugaShire** [comment]
Use google chrome

**Comment by briankendall** [comment]
I'm aware that it works in Chrome, but I strongly prefer to use Safari. And given that when the YouTube app is installed from the app store Safari does open links in the app, that suggests that there's a way to get it to work when sideloading YouTube++.

**Comment by briankendall** [comment]
Also I just tried it in Google Chrome anyway and it still didn't work!

**Comment by dmatora** [comment]
Youtube++ could at least include itself into iOS share dialog and accept links there
Without "open in" using it is a major pain

**Comment by briankendall** [comment]
@dmatora I've been using an app called Opener for that -- works great.

**Comment by Clayton630** [comment]
I installed the app but I still have to click on share button to open it in yt++, can you make it automatic ?
