### ISSUE TITLE
Snapchat?

### ISSUE THREAD

**Issue by qofa** [eni9889/ppsideloader#247]
What happened to Snapchat++?

**Comment by kaser2010** [comment]
???????????

**Comment by qofa** [comment]
Snapchat++ doesn't work anymore…will it be revived?

**Comment by ojinchurikio** [comment]
The developer posted on his twitter feed that there is currently no way to sideload Snapchat without having it cause issues.

The issues include "Could not connect to Network" or "unexpected crash" type of issues.

If I'm not mistaken, the project still lives but only for Jailbroken Devices!

Unknown Devil!

**Comment by crisdavid7341** [comment]
Works for now on the latest version of Snapchat
