### ISSUE TITLE
Failing to add my own tweak.

### ISSUE THREAD

**Issue by euroboy** [eni9889/ppsideloader#256]
Hello. I replaced empty app.ipa with ipa file I would like to tweak. Then added my tweak dylib file with its bundle file to an archive called pptweak.zip, and placed it to the root folder of the project. However, my tweak is not loading, I'm not seeing it in the app. Sorry if it's misleading, maybe someone can help.

**Comment by Sam-Ryan** [comment]
Hey man! Can you specify in which Ipa are you using?

**Comment by euroboy** [comment]
Hi. I'm using Snapchat ipa.

**Comment by Sam-Ryan** [comment]
So Snapchat is a bit complicated, make sure that your dylib is not conflicting With any other Snap++ method.. In another case try to use à previous version for The ipa

**Comment by euroboy** [comment]
I've tried many versions: 9.45.10, 10.7, 10.10, 10.12 - no success. Also my tweak hooks the app delegate applicationDidBecomeActive method, where I'm just adding a subview to UIWindow. Shouldn't be any conflict. Cannot figure out what is wrong.
