### ISSUE TITLE
Why codesign want access to my keychain?

### ISSUE THREAD

**Issue by blogdjmaster** [eni9889/ppsideloader#257]
When i run the app to install in my iphone, codesign want access to my keychain in the key "access". Why?

**Comment by Sam-Ryan** [comment]
Hi
Have you an issue in xCode? If yes can you provide The issue please. Screenchot is Highly appreciated

**Comment by blogdjmaster** [comment]
This.
![captura de pantalla 2017-08-04 a la s 6 51 13 p m](https://user-images.githubusercontent.com/29960705/28991516-1e3d04c0-7946-11e7-9374-9f785fde4b62.png)

**Comment by blogdjmaster** [comment]
Msg: codesign want access to key "access" on your keychain.

**Comment by blogdjmaster** [comment]
When i click on play, after seconds show that..

**Comment by Sam-Ryan** [comment]
It's because its probably the first time you build the ppsideloader project with your dev account.
You need to accept this to make the correct functionning of the project. If you dont allow codesign to acces the keychain, xCode cannot longer find your account.
Warmly

**Comment by blogdjmaster** [comment]
Isnt first time, im have 1 year using this tweak :/

**Comment by Sam-Ryan** [comment]
maybe you changed account during this period.. Anyway just accept this^^

**Comment by blogdjmaster** [comment]
hahahaha, ok, thanks.
