### ISSUE TITLE
IG++ Crashing

### ISSUE THREAD

**Issue by blogdjmaster** [eni9889/ppsideloader#259]
Hello, i have 5 days with the app crashing. Dont run. This open and close fastly. Anyone have this issue?

**Comment by beBoss** [comment]
It's not crushing. If you upload it/sideloading it to your phone with free apple licence, you can only use it for 7 days, then you have to reupload it again. If you have dev acc, then the app will on your phone as much as your licence is valid.

**Comment by blogdjmaster** [comment]
I have using this by months, but have one week with crash, dont work.
