### ISSUE TITLE
issue when you want to upload vidéo or photo 

### ISSUE THREAD

**Issue by DzMohaipa** [eni9889/ppsideloader#261]
fix issue upload  button on version 10.20.0 thanks

**Comment by Sam-Ryan** [comment]
Pourquoi la 10.2 Wesh  ?!

**Comment by mohadu313** [comment]
Mdrr tu patiente et c'est tout on taf dessu perso j'ai modifié l'erreur du button

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Sam-Ryan** [comment]
j'avais pas vu la version 10.20 lol. Je suis entrain de développer mn propree tweak donc j'attend plus apres Snap+.

**Comment by mohadu313** [comment]
Mdrr ton propre tweak 😂😂 t'as volé les hook d'où monsieur mdrrrr

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Sam-Ryan** [comment]
Je refait un tweak sur la base de snap+ gros. Mdrrr Tkt khey
