### ISSUE TITLE
Tweak not building

### ISSUE THREAD

**Issue by milkcrow** [eni9889/ppsideloader#263]
OVERWRITE_ORIGINAL_APP: true
KEEP_ORIGINAL_APP_NAME: true
REMOVE_PLUGINS: false
NAME_TWEAK_MS: false
EXTRACTING IPA
FOUND APP PATH: /Users/admin/Downloads/ppsideloader-master/temp/EXTRACTED_IPA/Payload/Twitter.app
USING PPTWEAK AT /Users/admin/Downloads/ppsideloader-master/pptweak.zip
EXTRACTING PP TWEAK
/Users/admin/Library/Developer/Xcode/DerivedData/ppsideloader-emrnabtjhhhxpaaswlmgiwyunajh/Build/Products/Debug-iphonesimulator/ppsideloader.app/
EXE IS EXECUTABLE
SET TRANSPORT SECURITY TO ALLOW ALL
SET Music Sharing Description for WhatsApp
Delete: Entry, ":NSAppleMusicUsageDescription", Does Not Exist
**TWEAK NAME: 73ea5185bd5e1e00cfa5a715.dylib
**mv: rename /Users/admin/Library/Developer/Xcode/DerivedData/ppsideloader-emrnabtjhhhxpaaswlmgiwyunajh/Build/Products/Debug-iphonesimulator/ppsideloader.app/pptweak.dylib to /Users/admin/Library/Developer/Xcode/DerivedData/ppsideloader-emrnabtjhhhxpaaswlmgiwyunajh/Build/Products/Debug-iphonesimulator/ppsideloader.app/73ea5185bd5e1e00cfa5a715.dylib: No such file or directory**
Binary is a fat binary with 2 archs.**
LC_CODE_SIGNATURE load command found. Remove it? [y/n] y
LC_CODE_SIGNATURE load command found. Remove it? [y/n] y

**Comment by JdelgadoV** [comment]
Excuse my ignorance but what do I do w what was sent to me ?
I was able to view it in GitHub. 
Can you help ?

**Comment by Avimael6** [comment]
Yes
