### ISSUE TITLE
Please update IG++ to latest version!!!

### ISSUE THREAD

**Issue by brynts** [eni9889/ppsideloader#269]
don't forget us, we are sideloaded users :(

**Comment by d3ibis** [comment]
u mean update codes, u can download latest cracked ipa and build it in ppsideloader project along with pptweak.zip (u can go to eni9889/pptweaks and download IG tweak & rename it to pptweak.zip)

its all mention in wiki.

**Comment by blogdjmaster** [comment]
Can you explain more please? i need do it.
