### ISSUE TITLE
Double Notifications

### ISSUE THREAD

**Issue by Element108** [eni9889/ppsideloader#27]
With Whatsapp++ i get double Notification for messages.
Example:
1. Notification with this text: "New Message from Kenny"
2. Notification with this text: "Kenny: Yo, Whatsupp"

to one of the two notifications shows the actual message.

My Settings in Xcode

	KEEP_ORIGINAL_APP_NAME: false

	OVERWRITE_ORIGINAL_APP: true
	
	CREATE_IPA_FILES: false

**Comment by Mehdman** [comment]
Same issue for me.

**Comment by eni9889** [comment]
I don't really know how to fix this sorry
