### ISSUE TITLE
Snapchat 

### ISSUE THREAD

**Issue by 7rb221** [eni9889/ppsideloader#271]
If I try to enter snapchat ++ with my account .. it says i try to enter in third-party app ! 

What is the solution ??

**Comment by d3ibis** [comment]
u can try downloading cracked ipa (which ill b difficult for SC as they're removing copies from uploading websites!!) and try to download (eni9889/pptweaks "snapchat one") rename it to pptweak.zip and put it beside app.ipa, build and try...btw, still working fine with me.
