### ISSUE TITLE
Build error starting Twitter v7.32

### ISSUE THREAD

**Issue by sadalhayat** [eni9889/ppsideloader#273]
Build error starting Twitter v7.32

Multiple commands produce '/Users/user/Library/Developer/Xcode/DerivedData/ppsideloader-cjjjspxzszacjocgtdepomcfwrge/Build/Products/Debug-iphoneos/ppsideloader.app/Info.plist':

1) Target 'ppsideloader' (project 'ppsideloader') has copy command from '/Users/user/Downloads/ipa/ppsideloader/ppsideloader_20180123/twitter-ppsideloader/Info.plist' to '/Users/user/Library/Developer/Xcode/DerivedData/ppsideloader-cjjjspxzszacjocgtdepomcfwrge/Build/Products/Debug-iphoneos/ppsideloader.app/Info.plist'

2) Target 'ppsideloader' (project 'ppsideloader') has process command with output '/Users/user/Library/Developer/Xcode/DerivedData/ppsideloader-cjjjspxzszacjocgtdepomcfwrge/Build/Products/Debug-iphoneos/ppsideloader.app/Info.plist'

**Comment by blogdjmaster** [comment]
I have same issue with IG++. You fixed?
