### ISSUE TITLE
App installation failed: illegal Bundle identifier

### ISSUE THREAD

**Issue by espilsad** [eni9889/ppsideloader#28]
When I try to install it everything builds and signs perfectly but upon installing (I think at the last step) I get the error message:

>App installation failed: 
This app contains an app extension with an illegal bundle identifier. App extension bundle identifiers must have a prefix consisting of their containing application's bundle identifier followed by a '.'.

**Comment by peter961785** [comment]
Try 
com.somethingrandom.appname
For the bundle identifier
replace somethingrandom & appname
