### ISSUE TITLE
Warning: The Copy Bundle Resources build phase contains this target's Info.plist file 'Info.plist'.

### ISSUE THREAD

**Issue by RajPatel0929** [eni9889/ppsideloader#30]
Warning: The Copy Bundle Resources build phase contains this target's Info.plist file 'Info.plist'.

**Comment by RajPatel0929** [comment]
I think this error was from starting now in my side

closed 
Thanks

**Comment by pcverbeek** [comment]
I have the same issue, how to fix? :(
