### ISSUE TITLE
unable to add app id because the "10" App id limit in "7" days has been exceeded

### ISSUE THREAD

**Issue by fmd6829** [eni9889/ppsideloader#31]
Hello, I've been installing applications to multiple devices and after this letter appeared, what is the solution please help, I want the way devices Unlimited

**Comment by al-muftah** [comment]
same issue here :(

**Comment by RajPatel0929** [comment]
same here


so I made new apple id and it is fixed.

**Comment by fmd6829** [comment]
Thank you calculate a new developer and the problem ended
