### ISSUE TITLE
[Snapchat] App installation failed

### ISSUE THREAD

**Issue by espilsad** [eni9889/ppsideloader#35]
Every time I try to install Snapchat++ I get this error:

>**App installation failed**
An unknown error has occurred.

**Comment by RajPatel0929** [comment]
restart xcode...
I had that error too by restarting xcode and redoing it fixed it... but after install app open but close right away :(

**Comment by espilsad** [comment]
Still didn't work for me :(

**Comment by eni9889** [comment]
Please re-download ppsideloader and run again
