### ISSUE TITLE
[Snapchat] Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by thinkv** [eni9889/ppsideloader#36]
`EXTRACTING PP TWEAK
[/Users/v/Downloads/ppsideloader-master 3/temp/pptweak.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/v/Downloads/ppsideloader-master 3/temp/pptweak.zip or
        /Users/v/Downloads/ppsideloader-master 3/temp/pptweak.zip.zip, and cannot find /Users/v/Downloads/ppsideloader-master 3/temp/pptweak.zip.ZIP, period.
/Users/v/Library/Developer/Xcode/DerivedData/ppsideloader-awgsilsforimgsaalluviilqzlvk/Build/Products/Debug-iphoneos/ppsideloader.app/
EXE IS EXECUTABLE
KEEP_ORIGINAL_APP_NAME IS NOT ENABLED
Couldn't open file @executable_path/pptweak.dylib
SIGNING: *.dylib
SIGNING: FINAL BINARY
Command /bin/sh failed with exit code 1`

**Comment by mayankchhabra** [comment]
+1 :(

**Comment by costee** [comment]
+1 :/

**Comment by espilsad** [comment]
Have you tried everything from the closed issues?

> In your target you have to go to Build phases -> Run Script -> Run script only when installing
> run script
> ![run script2](https://cloud.githubusercontent.com/assets/17473295/15009594/88191928-11e7-11e6-9733-ad2ac1f51148.jpg)
>

**Comment by costee** [comment]
This way the app installs but crashes upon launch (I enabled the dev profile in Settings) 😕

**Comment by mikhilp** [comment]
+1 Occurred with Messenger++

**Comment by eni9889** [comment]
Please re-download ppsideloader project and run again
