### ISSUE TITLE
Can someone please tell me how to remove the ads. cause am going to delete the app

### ISSUE THREAD

**Issue by claydon99** [eni9889/ppsideloader#38]
Can someone please tell me how to remove the ads. cause am going to delete the app

**Comment by redaizo** [comment]
There is donation to supporte de Devs 2 dollars per app or 7 dollars to get rid of ads on every app, check the setting inside for instance Snap++

**Comment by iiMshl** [comment]
You can donate to the developers 2$ per app to remove the ads or 7$ to remove the ads on all ++ apps.... but there is an option to remove the apps for 1.5/2 weeks and it's that you tweet about the app... in the ++ app(Snapchat, Instagram, Twitter, Youtube, WhatsApp...) locate the "++"(Snap+,IG+,WA+,YT+..) settings and you will find a heart icon in the top right corner tap it and tweet and bam... no more ads for couple of weeks.. 

Hope that helped.

**Comment by al-muftah** [comment]
https://www.reddit.com/r/jailbreak/comments/4jzji1/giveaway_its_that_time_again_tweaks_premium/?

try ur luck 👍
