### ISSUE TITLE
appIdId

### ISSUE THREAD

**Issue by VIC3-420** [eni9889/ppsideloader#4]
I keep on getting this error in Xcode "No value was provided for the parameter 'appIdId' " please help me I was using Instagram and Youtube IPA's

**Comment by eni9889** [comment]
What Xcode version are you using?

**Comment by VIC3-420** [comment]
I'm using xcode 7.2 for some odd reason 7.3 isn't in the update tab in the app store

**Comment by VIC3-420** [comment]
Never mind I got it to work
