### ISSUE TITLE
Instagram Issue

### ISSUE THREAD

**Issue by segongora** [eni9889/ppsideloader#44]
![captura de pantalla 2016-05-09 a las 18 04 57](https://cloud.githubusercontent.com/assets/19274985/15130782/971baec2-1610-11e6-81d8-8ac5bab68116.png)

What can I do?

**Comment by eni9889** [comment]
it looks like a signing issue. Please re-download ppsideloader and run again

**Comment by segongora** [comment]
I have re-downloaded ppsideloader and this continues happening. Im a paid user, any help?? I use snapchat perfectly fine.
