### ISSUE TITLE
Snapchat ++ wont open

### ISSUE THREAD

**Issue by rlpanama** [eni9889/ppsideloader#45]
Okay I need help like right now because snapchat++ wont even open now, and I payed 7$ and everything, and now it wont work please help me

**Comment by al-muftah** [comment]
you are not alone, same here

**Comment by redaizo** [comment]
Easy guys, reinstall Snap++ all your app will work fine, in think there some signing certificat issue, apple has made some change, my bet, any way open the Xcode project with snap ipa, click the "fix issue" button run the build, all your "++" apps will work fine after one install, at least for me, thats what i did

**Comment by dagsommer** [comment]
Same problem here

**Comment by eni9889** [comment]
Please make sure you are using a decrypted IPA. IPA from iTunes won't work also it is possible you have a broken IPA so try another one

**Comment by djaykaushik** [comment]
I have the same Problem in Snapchat but What I do,
Step 1 - Uninstall Snapchat
Step 2 - Restart your Smartphone
Step 3 - After restart Go to Settings>>apps>>options>>reset app preference 
And Now my Snapchat is Working Fine ([source](http://technoedit.com/2017/04/how-to-solve-wont-open-error/))
