### ISSUE TITLE
Instagram 8.0 Crash with Full function

### ISSUE THREAD

**Issue by mastermark1983** [eni9889/ppsideloader#50]
Instagram 8.0 Crash with Full function
need some update ;)
Thx Grtz Mark iP4L Team

**Comment by mastermark1983** [comment]
Custom feed disable works fine ;)

**Comment by brynts** [comment]
click IGExperiment setting, then crash

**Comment by eni9889** [comment]
@mastermark1983 do you mean full screen crashes?

**Comment by mastermark1983** [comment]
Custom feed off works Full feed Crash Insta
