### ISSUE TITLE
Instagram 8.0 Crash

### ISSUE THREAD

**Issue by MarcoS3935** [eni9889/ppsideloader#51]
I downloaded a supposedly cracked version of instagram 8.0 from appcake and loaded it onto my iphone 6 running ios 9.3.1 and it crashes when i open the app

**Comment by MarcoS3935** [comment]
I just fixed my problem. You just need to make sure that you downloaded a cracked version of instagram. I guess the one i downloaded first was broken or not cracked.

**Comment by segongora** [comment]
where did you get the instagram cracked ipa? i don't seem to find it anywhere

**Comment by joeafflitto** [comment]
@segongora I found a way throgh the VShare PC application where you download it to the computer and from the VShare desktop app you can browse to the folder it downloads the IPA then transfer it over to my Macintosh to compile the build.
