### ISSUE TITLE
SNAPCHAT CRASH WHEN OPENING

### ISSUE THREAD

**Issue by DxVasily** [eni9889/ppsideloader#55]
after install snapchat appt does not open it crashes.

**Comment by DxVasily** [comment]
Can any one help???

**Comment by VIC3-420** [comment]
Try rebuild it that happened to me on the latest version on snapchat and I reinstalled it and it worked.

**Comment by DanielTran15** [comment]
You have to rebuild it every **7 days** now, Apple has changed the free developer certificate rules.

**Comment by h1x0rz3r0** [comment]
Try to set Bulild Version (OS) to 8.0 or 9.3

Worked for me:

SnapChat: 9.3
InstaGram: 8.0
Facebook: 8.0
Vine: 8.0

Should help

**Comment by h1x0rz3r0** [comment]
Forgot to say: http://www.appdb.com is a good site for IPA Download (only use for FREE Apps only, i don't support piracy)

**Comment by h1x0rz3r0** [comment]
http://www.appdb.cc
