### ISSUE TITLE
WhatsApp ++ Recover iCloud Backup

### ISSUE THREAD

**Issue by Bl4ckC1rcl3** [eni9889/ppsideloader#56]
Hi, I'm testing your awesome "++ tweaks" and when I install WhatsApp ++ is unable to recover the messages stored on iCloud, I think it's a problem with the App ID, how I can fix this?

**Comment by musio2** [comment]
is it possible to back up both WhatsApp (original) and WhatsApp ++ at the same time? (keeping data saparate) 

Thank you!
