### ISSUE TITLE
Snapchat++ Won't Download

### ISSUE THREAD

**Issue by monkeyman0510** [eni9889/ppsideloader#57]
Every time that I try to download Snapchat++, I receive this error:
Unable to launch /private/var/containers/Bundle/Application/12BDDBA3-744A-4E8C-BF45-7B6E0B62896C/ppsideloader.app

Please help

**Comment by Abdullah-alonzi** [comment]
.

**Comment by Abdullah-alonzi** [comment]
a10c945b4f22add5bebdb36642e8523481bc5c6d
