### ISSUE TITLE
Snapchat 9.30.0.0

### ISSUE THREAD

**Issue by ajhen16** [eni9889/ppsideloader#59]
I cannot even use this version of snapchat because so many things do not work inside of the app, cannot record longer than 10 seconds, app always crashes and then makes me re-login to get rid of ads, i always have to put my settings back to how i had them. So i have to run with 9.28.0.0 and its so outdated so i dont have all the new features and it often crashes from being outdated.

**Comment by joeafflitto** [comment]
Where are you getting your IPA files?

**Comment by ajhen16** [comment]
Links from iphone cake mostly

**Comment by learn2reid** [comment]
I have the same problems, please advise.

**Comment by ajhen16** [comment]
I found that the ipa file I must have been using were somehow corrupt because I located a verified upload and the one I'm using for 9.31 is very stable and I have zero issues with it. 

Thanks, 
Adam Henley

**Comment by segongora** [comment]
Where did you found your ipa file? @ajhen16

**Comment by joeafflitto** [comment]
appdb.cc supposedly has the sideloaded apps pre-built... waiting to test it out myself. 

(Don't use the above information for piracy)

**Comment by ajhen16** [comment]
I don't want to promote piracy but if you can message me directly I'll be able to better assist you.

**Comment by segongora** [comment]
Thanks @ajhen16 but I don't know where I can message you directly. Any suggestions?

**Comment by ajhen16** [comment]
Message me on Twitter? Same handle on here.
