### ISSUE TITLE
CFBundleExecutable

### ISSUE THREAD

**Issue by al-muftah** [eni9889/ppsideloader#6]
Can't install application
ppsideloader.app cannot be installed on Jaber's iPhone 6. ppsideloader.app does not contain a valid Info.plist

(“CFBundleExecutable” specifies a file that is not executable)

http://store1.up-00.com/2016-04/146082206401281.png

**Comment by ntassani** [comment]
Thats happening to me with the version 25 of facebook... Not with the actual version... So, in app messenger cant work.

**Comment by nullr1ver** [comment]
You can fix that by following these steps:

1) Rename yourapp_resigned.ipa to yourapp_resigned.zip
2) Unzip yourapp_resigned.zip to yourapp_resigned folder
3) Launch Terminal, type command: $ cd yourapp_resigned folder
4) Type command: $ chmod +x Payload/yourapp (here yourapp is executable file)
5) Type command $ zip -r -T -y yourapp_resigned_fixed.ipa Payload
6) Try to install yourapp_resigned_fixed.ipa to your phone.

Hope I helped you!

**Comment by Jwiggiff** [comment]
Having the same problem. @nullr1ver Does not seem to work.

**Comment by nullr1ver** [comment]
Hmm, worked for me @Jwiggiff

**Comment by jcm36** [comment]
Hey, @nullr1ver and @Jwiggiff i'm getting this same error with all of the apps I have tried (Facebook, youtube and snapchat).

Is there a slack room or anything where we could chat to try and get to the bottom of this bug?

Thanks

**Comment by eni9889** [comment]
@jcm36 please try the latest commit https://github.com/eni9889/ppsideloader/commit/0e7434dc60f48d4f46acdafca81cf15e6084970b

**Comment by Jwiggiff** [comment]
@nullr1ver nvm I tried it again and it worked

**Comment by al-muftah** [comment]
Thx it works, also i install whatsapp ++ but dose it support iPad?

**Comment by ntassani** [comment]
But no facebook 25 :(
