### ISSUE TITLE
/Users/mackbook/Library/Developer/Xcode/DerivedData/ppsideloader-eumzqlqrnxsnufhclgyigjkphzqb/Build/Products/Debug-iphoneos/ppsideloader.app/*.dylib: No such file or directory

### ISSUE THREAD

**Issue by yaweeh123** [eni9889/ppsideloader#61]
/Users/mackbook/Library/Developer/Xcode/DerivedData/ppsideloader-eumzqlqrnxsnufhclgyigjkphzqb/Build/Products/Debug-iphoneos/ppsideloader.app/*.dylib: No such file or directory   

whats the problem is here ...?

**Comment by moh0sw** [comment]
same problem !!!!

**Comment by saeedkunna** [comment]
me too !?

**Comment by saalmaaan** [comment]
# **same problem :(**

**Comment by saalmaaan** [comment]
another problem !!

**Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure**

**Comment by saalmaaan** [comment]
I think I found the solution !!
I was having the same problem earlier ..
**Did you update or install the Xcode program recently !!**
Then you got the problem ??

there is missing files you need to install it ... to solve the issue
After using the the old method to install the TweakPatcher using terminal 
During the process, I think it was the missing files are installed !!

Try the it 
https://github.com/Defying/TweakPatcher

**Comment by yaweeh123** [comment]
i know theres something missing but what causes for this problem i try older folder for ppsideloader working fine

**Comment by moh0sw** [comment]
problem solved! 👍
