### ISSUE TITLE
Sanp+ 

### ISSUE THREAD

**Issue by AlThani** [eni9889/ppsideloader#69]
I’ve tried to build and sideload snapchat++ but I always get Snap+ v1.6r-6  instead of the latest version 
which is v1.6r-9 at the time of this post.

This is also seems to happen with me with other ++ tweaks such as whatsapp++ and youtube++.

Any idea?

**Comment by al-muftah** [comment]
you are not alone, Same here

**Comment by AlThani** [comment]
@al-muftah it's fixed now. @eni9889 Thank you
