### ISSUE TITLE
Snapchat++ Crashes every week?

### ISSUE THREAD

**Issue by qttt123** [eni9889/ppsideloader#70]
Every single week Snapchat++ decides to not open anymore, is there any work around this?

**Comment by al-muftah** [comment]
the free developer certificate validation for 1 week

**Comment by ajhen16** [comment]
how do i fix this?

**Comment by joeafflitto** [comment]
Dude. Read every other thread and the instructions itself. You cannot "fix" it. You can apply to be a developer and pay $100 per year to have longer lasting certificates. Otherwise, you have to rebuild every 7 days.

**Comment by ajhen16** [comment]
Take it easy

Thanks, 
Adam Henley

**Comment by joeafflitto** [comment]
Don't mean to be hostile. But it's in the instructions and has been asked before but I continue to receive emails asking for help. 

Joe

**Comment by orgreats** [comment]
Hi how to be devoloper for snap+ and whatsapp+ for 1 year ?

**Comment by orgreats** [comment]
I have so many people want it

**Comment by joeafflitto** [comment]
You must apply for an account at the dev center. https://developer.apple.com/develop/
