### ISSUE TITLE
Hiding discovery doesn't work

### ISSUE THREAD

**Issue by ale-nerd** [eni9889/ppsideloader#79]
Hiding discovery or live stories doesn't work

**Comment by liamokay** [comment]
what snapchat version are you using

**Comment by ale-nerd** [comment]
9.31.1 pretty much one that came before big update one. The one for May 25th. All other features working, only those 2 doesn't

**Comment by al-muftah** [comment]
you are not alone, same here

**Comment by neek247** [comment]
same, been like this for a long while and still is an issue..
