### ISSUE TITLE
ld: warning: directory not found for option '-L/Users/Jason/Downloads/ppsideloader-master-2/uasharedtools'

### ISSUE THREAD

**Issue by ToothyArmy** [eni9889/ppsideloader#8]
This happens every time I try.

**Comment by AlphaT3ch** [comment]
How did you fix this? I'm having the same issue here, but you closed it.

**Comment by jbperezf** [comment]
yeah me too!

**Comment by ToothyArmy** [comment]
For this I went to the first place I found out how to get snap+ and used that instead of this way since it didn't work. Though it did work for Instagram and YouTube.

**Comment by ToothyArmy** [comment]
https://github.com/Defying/TweakPatcher
