### ISSUE TITLE
Snapchat banned

### ISSUE THREAD

**Issue by liamokay** [eni9889/ppsideloader#83]
Getting temp banned from snapchat???

**Comment by joeafflitto** [comment]
Did this app get you temp banned?? Your first temp ban should only be a couple hours, just delete the modified version, reinstall the normal snapchat, and try in around 4 hours to sign back in (that's how long my first temp took). They get longer every time though, and I've gotten three, so I can't tell you if 4 is the magic number for a perm ban.

**Comment by liamokay** [comment]
Yeah, it did... Arghhhhhh so annoying. Thanks though!

**Comment by joeafflitto** [comment]
Scariest moment in my life was thinking I'd lose all my streaks. Just try to stay away from hacks, I just use the trick to screenshot without alerting with no hacks. 

Joe

**Comment by liamokay** [comment]
Still not unbanned and its been 8 hours.....

**Comment by joeafflitto** [comment]
Did you uninstall the hacked version? If not, when you try to sign in, does it say its specifically temporary?

**Comment by liamokay** [comment]
Yep, uninstalled it and its still temp banned. "You are temporarily banned, to find out why you may be banned......"

**Comment by joeafflitto** [comment]
Have you been temp banned before?

**Comment by liamokay** [comment]
nope

**Comment by joeafflitto** [comment]
Try going to www.snapchat.com/locked (or something like that, I'd check the message you get when you try to sign in.)

**Comment by leviwooten** [comment]
what's the hacked version of snapchat that you used called? i need it because i was device banned

**Comment by shield2021** [comment]
Je cherche une technique banne Snapchat qui en a s'il vous plaît
