### ISSUE TITLE
does snapchat 9.32.2 hack work?

### ISSUE THREAD

**Issue by rire98** [eni9889/ppsideloader#84]

**Comment by seiterseiter** [comment]
Yes

**Comment by rire98** [comment]
Are the hack running perfect on 9.32.2 does it closed sometimes  the app

**Comment by rire98** [comment]
thank you :+1:

**Comment by fa666ot** [comment]
can someone link me to a download of 9.32.2 plz??? i can only find an iso for 9.32.1 & cant find 9.32.2 anywhere x__x

**Comment by hackdafootball** [comment]
@fa666ot you can download cracked ipa's from appcake.com

**Comment by seiterseiter** [comment]
Its iphonecake.com not appcake.com

**Comment by fa666ot** [comment]
@hackdafootball @seiterseiter THANK YOU!!! ive never even heard about this site, i just always used appaddict
