### ISSUE TITLE
i keep getting these error messages, someone please help.

### ISSUE THREAD

**Issue by amouminah** [eni9889/ppsideloader#91]
![screen shot 2016-06-11 at 2 16 28 pm](https://cloud.githubusercontent.com/assets/19872287/15984776/a49d7484-2fdf-11e6-813d-4f12e9a67bfc.png)

**Comment by yaweeh123** [comment]
hi there 

try  to download a new ppsideloader  then but the app u want to modify it and change the name for the application to 

app.ipa 

thats it
