### ISSUE TITLE
Overwrite ++ Apps

### ISSUE THREAD

**Issue by al-muftah** [eni9889/ppsideloader#95]
Dear All,
is there any way I can overwrite the apps instead of delete it and install fresh copy ?

**Comment by joeafflitto** [comment]
Do you have a developer account?

**Comment by al-muftah** [comment]
Yes

Sent from my iPad

On Jun 14, 2016, at 5:33 PM, joeafflitto <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you have a developer account?

> On Jun 14, 2016, at 02:13, al-muftah <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> Dear All,
> is there any way I can overwrite the apps instead of delete it and install fresh copy ?
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

-
