### ISSUE TITLE
9.32.3.0 Does it work?

### ISSUE THREAD

**Issue by Billabong24** [eni9889/ppsideloader#96]
I am at the point after trusting the developer on my phone, but the app force quits when i click on it. Help?

**Comment by hossein1378** [comment]
yes plz help me my app snapchat++ get crash and more INSTAGRAM ++ AND YOUTUBE++ all of them ant i use very careful this turtrial plz help me !!!

**Comment by Reedaa** [comment]
Me too, I cant launch Snapchat

**Comment by NickClements1** [comment]
Just reinstall from xcode.

**Comment by Billabong24** [comment]
I reinstalled it and it still didn't work

**Comment by joeafflitto** [comment]
It's working for me (iOS 9.3.2) I downloaded a fresh copy of the side loader and an IPA from AppCake. It took like 30 minutes to build, but it worked.

**Comment by al-muftah** [comment]
its work for me
