### ISSUE TITLE
iOS 10 

### ISSUE THREAD

**Issue by NickClements1** [eni9889/ppsideloader#97]
Occasionally while using snapchat++ the phone will crash and restart. 
Notifications not working either.

**Comment by Billabong24** [comment]
Also I can't just take a picture, I have to take a video every time.

**Comment by joeafflitto** [comment]
I wouldn't expect just about anything to work on the first beta of a major update from Apple, they're all a mess. I'd say if some apps from the app store don't work, a side loaded modified version of Snapchat wouldn't work.

**Comment by shusain93** [comment]
I agree with joeafflitto -- it's beta one. If you think this is the tool ppsideloader's fault you should be on a developer beta. Most likely this is a combination of screwy iOS 10 and the fact that tweaks never work on new iOS versions

**Comment by joeafflitto** [comment]
Update: Known workaround uploaded by developer of tweak for notification issues.
