### ISSUE TITLE
Apps Crashing After installing!

### ISSUE THREAD

**Issue by Nimish95** [eni9889/ppsideloader#99]
All of a sudden apps started to crash as soon as I open them. It happened to me today and the error that appears is  **dyld: Library not loaded: /usr/lib/libuasharedanaltyics.dylib
  Referenced from: /var/mobile/Containers/Bundle/Application/FEF62F9C-8A25-42A9-9BC1-DDCE9C8AF3C5/ppsideloader.app/pptweak.dylib
  Reason: image not found**
I never faced such problems. What I did was, I deleted the Facebook app and then I ran the Xcode project. It installed successfully but crashes on opening!

**Comment by MTShare** [comment]
same for me
